<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class CrmCreateLeadRequestTypedFields extends WireModel
{
    public const FIELDS = ['expected_definition_version' => ['property' => 'expectedDefinitionVersion', 'type' => ['scalar' => 'int']], 'values' => ['property' => 'values', 'type' => ['model' => 'Factuarea\\Sdk\\Custom\\Crm\\Model\\CrmCreateLeadRequestTypedFieldsValues']]];

    public const SCHEMA = ['type' => 'object', 'properties' => ['expected_definition_version' => ['type' => 'integer', 'minimum' => 0], 'values' => ['type' => 'object', 'properties' => ['value_version' => ['type' => 'integer', 'minimum' => 0], 'values' => ['type' => 'array', 'items' => ['type' => 'object', 'properties' => ['field_id' => ['type' => 'string', 'minLength' => 1, 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$', 'format' => 'uuid'], 'field_version' => ['type' => 'integer', 'minimum' => 1], 'value' => ['type' => ['string', 'number', 'boolean', 'null', 'array'], 'items' => ['type' => 'string']]], 'additionalProperties' => false, 'required' => ['field_id', 'field_version', 'value']], 'maxItems' => 100]], 'additionalProperties' => false, 'required' => ['value_version', 'values']]], 'additionalProperties' => false, 'required' => ['expected_definition_version', 'values']];

    /**
     * @param  int  $expectedDefinitionVersion
     * @param  \Factuarea\Sdk\Custom\Crm\Model\CrmCreateLeadRequestTypedFieldsValues  $values
     */
    public function __construct(
        public int $expectedDefinitionVersion,
        public \Factuarea\Sdk\Custom\Crm\Model\CrmCreateLeadRequestTypedFieldsValues $values,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
