<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class CrmContactNormalizationPreviewAcceptedValuesTypedFields extends WireModel
{
    public const FIELDS = ['expected_definition_version' => ['property' => 'expectedDefinitionVersion', 'type' => ['scalar' => 'int']], 'values' => ['property' => 'values', 'type' => ['model' => 'Factuarea\\Sdk\\Custom\\Crm\\Model\\CrmContactNormalizationPreviewAcceptedValuesTypedFieldsValues']]];

    public const SCHEMA = ['type' => 'object', 'additionalProperties' => false, 'properties' => ['expected_definition_version' => ['type' => 'integer', 'minimum' => 0], 'values' => ['type' => 'object', 'additionalProperties' => false, 'properties' => ['value_version' => ['type' => 'integer', 'minimum' => 0], 'values' => ['type' => 'array', 'maxItems' => 100, 'items' => ['type' => 'object', 'additionalProperties' => false, 'properties' => ['field_id' => ['type' => 'string', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], 'field_version' => ['type' => 'integer', 'minimum' => 1], 'value' => ['anyOf' => [['type' => 'string', 'maxLength' => 4000, 'pattern' => '^[^\\u0000-\\u0008\\u000b\\u000c\\u000e-\\u001f\\u007f]*$'], ['type' => 'boolean'], ['type' => 'array', 'items' => ['type' => 'string', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], 'maxItems' => 100], ['type' => 'null']]]], 'required' => ['field_id', 'field_version', 'value']]]], 'required' => ['value_version', 'values']]], 'required' => ['expected_definition_version', 'values']];

    /**
     * @param  int  $expectedDefinitionVersion
     * @param  \Factuarea\Sdk\Custom\Crm\Model\CrmContactNormalizationPreviewAcceptedValuesTypedFieldsValues  $values
     */
    public function __construct(
        public int $expectedDefinitionVersion,
        public \Factuarea\Sdk\Custom\Crm\Model\CrmContactNormalizationPreviewAcceptedValuesTypedFieldsValues $values,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
