<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class CrmGetLeadStatsParameters extends WireModel
{
    public const FIELDS = ['Factuarea-Version' => ['property' => 'factuareaVersion', 'type' => ['scalar' => 'string']], 'X-Active-Profile' => ['property' => 'xActiveProfile', 'type' => ['scalar' => 'string']], 'filters' => ['property' => 'filters', 'type' => ['scalar' => 'string']]];

    public const SCHEMA = ['type' => 'object', 'additionalProperties' => false, 'properties' => ['Factuarea-Version' => ['type' => 'string', 'format' => 'date', 'example' => '2026-06-01'], 'X-Active-Profile' => ['type' => 'string', 'format' => 'uuid', 'example' => '01931b3e-7c4a-7f2e-9a8b-3c5d6e7f8a0c'], 'filters' => ['type' => 'string', 'maxLength' => 65536, 'contentMediaType' => 'application/json', 'contentSchema' => ['$ref' => '#/components/schemas/LeadFilters'], 'description' => 'JSON string containing closed Lead filters. Current field and record permissions precede filtering, counts and pagination.']], 'required' => []];

    /**
     * @param  string|Omitted  $factuareaVersion
     * @param  string|Omitted  $xActiveProfile
     * @param  string|Omitted  $filters
     */
    public function __construct(
        public string|Omitted $factuareaVersion = Omitted::Value,
        public string|Omitted $xActiveProfile = Omitted::Value,
        public string|Omitted $filters = Omitted::Value,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
