<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class KnowledgeCategorySaveRequest extends WireModel
{
    public const FIELDS = ['taxonomy_id' => ['property' => 'taxonomyId', 'type' => ['scalar' => 'string']], 'expected_taxonomy_version' => ['property' => 'expectedTaxonomyVersion', 'type' => ['scalar' => 'int']], 'expected_version' => ['property' => 'expectedVersion', 'type' => ['union' => [['scalar' => 'int'], ['scalar' => 'null']]]], 'name' => ['property' => 'name', 'type' => ['scalar' => 'string']], 'slug' => ['property' => 'slug', 'type' => ['scalar' => 'string']], 'parent_id' => ['property' => 'parentId', 'type' => ['union' => [['scalar' => 'string'], ['scalar' => 'null']]]], 'visibility' => ['property' => 'visibility', 'type' => ['scalar' => 'string']], 'status' => ['property' => 'status', 'type' => ['scalar' => 'string']], 'id' => ['property' => 'id', 'type' => ['scalar' => 'string']]];

    public const SCHEMA = ['type' => 'object', 'properties' => ['id' => ['type' => 'string', 'format' => 'uuid', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], 'taxonomy_id' => ['type' => 'string', 'format' => 'uuid', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], 'expected_taxonomy_version' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 9223372036854775806], 'expected_version' => ['anyOf' => [['type' => 'integer', 'minimum' => 1, 'maximum' => 9223372036854775806], ['type' => 'null']]], 'name' => ['type' => 'string', 'minLength' => 1, 'maxLength' => 150], 'slug' => ['type' => 'string', 'minLength' => 1, 'maxLength' => 120, 'pattern' => '^[a-z0-9]+(?:-[a-z0-9]+)*$'], 'parent_id' => ['anyOf' => [['type' => 'string', 'format' => 'uuid', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], ['type' => 'null']]], 'visibility' => ['type' => 'string', 'enum' => ['internal', 'portal', 'public']], 'status' => ['type' => 'string', 'enum' => ['active', 'archived']]], 'required' => ['taxonomy_id', 'expected_taxonomy_version', 'expected_version', 'name', 'slug', 'parent_id', 'visibility', 'status'], 'additionalProperties' => false, 'oneOf' => [['properties' => ['expected_version' => ['type' => 'null']], 'not' => ['required' => ['id']]], ['required' => ['id'], 'properties' => ['expected_version' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 9223372036854775806]]]], 'description' => 'Closed native category intent. Creation omits id and sets expected_version to null; editing uses the existing id and original positive expected_version. expected_taxonomy_version is the original taxonomy CAS. parent_id is present and null only for an explicit root. name is nonblank; slug is immutable for an existing category. No effect, actor, Company or authorization is supplied in the body.', 'title' => 'KnowledgeCategorySaveRequest'];

    /**
     * @param  string  $taxonomyId
     * @param  int  $expectedTaxonomyVersion
     * @param  int|null  $expectedVersion
     * @param  string  $name
     * @param  string  $slug
     * @param  string|null  $parentId
     * @param  string  $visibility
     * @param  string  $status
     * @param  string|Omitted  $id
     */
    public function __construct(
        public string $taxonomyId,
        public int $expectedTaxonomyVersion,
        public ?int $expectedVersion,
        public string $name,
        public string $slug,
        public ?string $parentId,
        public string $visibility,
        public string $status,
        public string|Omitted $id = Omitted::Value,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
