<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class KnowledgeArticleRevision extends WireModel
{
    public const FIELDS = ['id' => ['property' => 'id', 'type' => ['scalar' => 'string']], 'version' => ['property' => 'version', 'type' => ['scalar' => 'int']], 'revision_number' => ['property' => 'revisionNumber', 'type' => ['scalar' => 'int']], 'title' => ['property' => 'title', 'type' => ['scalar' => 'string']], 'body' => ['property' => 'body', 'type' => ['scalar' => 'string']], 'editorial_locale' => ['property' => 'editorialLocale', 'type' => ['scalar' => 'string']], 'category_ids' => ['property' => 'categoryIds', 'type' => ['items' => ['scalar' => 'string']]], 'review_state' => ['property' => 'reviewState', 'type' => ['scalar' => 'string']]];

    public const SCHEMA = ['type' => 'object', 'additionalProperties' => false, 'properties' => ['id' => ['type' => 'string', 'format' => 'uuid', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], 'version' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 9223372036854775807], 'title' => ['type' => 'string', 'minLength' => 1, 'maxLength' => 240], 'body' => ['type' => 'string', 'minLength' => 1, 'maxLength' => 100000], 'editorial_locale' => ['type' => 'string', 'enum' => ['es', 'en', 'ca']], 'category_ids' => ['type' => 'array', 'items' => ['type' => 'string', 'format' => 'uuid', 'pattern' => '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'], 'maxItems' => 50, 'uniqueItems' => true], 'revision_number' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 9223372036854775807], 'review_state' => ['type' => 'string', 'enum' => ['draft', 'review', 'approved']]], 'required' => ['id', 'version', 'revision_number'], 'title' => 'KnowledgeArticleRevision'];

    /**
     * @param  string  $id
     * @param  int  $version
     * @param  int  $revisionNumber
     * @param  string|Omitted  $title
     * @param  string|Omitted  $body
     * @param  string|Omitted  $editorialLocale
     * @param  list<string>|Omitted  $categoryIds
     * @param  string|Omitted  $reviewState
     */
    public function __construct(
        public string $id,
        public int $version,
        public int $revisionNumber,
        public string|Omitted $title = Omitted::Value,
        public string|Omitted $body = Omitted::Value,
        public string|Omitted $editorialLocale = Omitted::Value,
        public array|Omitted $categoryIds = Omitted::Value,
        public string|Omitted $reviewState = Omitted::Value,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
