<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class PipelineStagePlaybookBlockingRulesItemVariant1 extends WireModel
{
    public const FIELDS = ['kind' => ['property' => 'kind', 'type' => ['scalar' => 'string']], 'question_key' => ['property' => 'questionKey', 'type' => ['scalar' => 'string']]];

    public const SCHEMA = ['type' => 'object', 'additionalProperties' => false, 'properties' => ['kind' => ['type' => 'string', 'const' => 'question_required'], 'question_key' => ['type' => 'string']], 'required' => ['kind', 'question_key']];

    /**
     * @param  string  $kind
     * @param  string  $questionKey
     */
    public function __construct(
        public string $kind,
        public string $questionKey,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
