<?php

/** Generated by tools/generate-crm.py from spec/crm-openapi.json. */

declare(strict_types=1);

namespace Factuarea\Sdk\Custom\Crm\Model;

use Factuarea\Sdk\Custom\Crm\Omitted;
use Factuarea\Sdk\Custom\Crm\Schema;
use Factuarea\Sdk\Custom\Crm\WireModel;

final class PipelineSaveLossReasonRequest extends WireModel
{
    public const FIELDS = ['expected_version' => ['property' => 'expectedVersion', 'type' => ['scalar' => 'int']], 'id' => ['property' => 'id', 'type' => ['scalar' => 'string']], 'label' => ['property' => 'label', 'type' => ['scalar' => 'string']], 'explanation_required' => ['property' => 'explanationRequired', 'type' => ['scalar' => 'bool']], 'status' => ['property' => 'status', 'type' => ['scalar' => 'string']], 'confirmed' => ['property' => 'confirmed', 'type' => ['scalar' => 'bool']]];

    public const SCHEMA = ['type' => 'object', 'additionalProperties' => false, 'properties' => ['id' => ['type' => 'string', 'format' => 'uuid'], 'expected_version' => ['type' => 'integer', 'minimum' => 1], 'label' => ['type' => 'string', 'minLength' => 1, 'maxLength' => 150], 'explanation_required' => ['type' => 'boolean'], 'status' => ['type' => 'string', 'enum' => ['active', 'archived']], 'confirmed' => ['type' => 'boolean']], 'required' => ['expected_version'], 'allOf' => [['if' => ['not' => ['required' => ['id']]], 'then' => ['required' => ['label']]], ['if' => ['properties' => ['status' => ['const' => 'archived']], 'required' => ['status']], 'then' => ['required' => ['id', 'confirmed'], 'properties' => ['confirmed' => ['const' => true]]]]], 'title' => 'PipelineSaveLossReasonRequest'];

    /**
     * @param  int  $expectedVersion
     * @param  string|Omitted  $id
     * @param  string|Omitted  $label
     * @param  bool|Omitted  $explanationRequired
     * @param  string|Omitted  $status
     * @param  bool|Omitted  $confirmed
     */
    public function __construct(
        public int $expectedVersion,
        public string|Omitted $id = Omitted::Value,
        public string|Omitted $label = Omitted::Value,
        public bool|Omitted $explanationRequired = Omitted::Value,
        public string|Omitted $status = Omitted::Value,
        public bool|Omitted $confirmed = Omitted::Value,
    ) {
        Schema::validate(self::SCHEMA, $this->jsonSerialize());
    }
}
