<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1WebhookEndpointsDeleteRequest
{
    /**
     *
     * @var string $webhookEndpoint
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=webhook_endpoint')]
    public string $webhookEndpoint;

    /**
     * @param  string  $webhookEndpoint
     * @phpstan-pure
     */
    public function __construct(string $webhookEndpoint)
    {
        $this->webhookEndpoint = $webhookEndpoint;
    }
}