<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;


/** Return status. Five published values: `requested` (asked for and awaiting a decision), `approved` (accepted and numbered), `received` (the goods came back in), `refunded` (the money went back, the end of the road) and `rejected` (turned down, also terminal). Exact match on `status`. */
enum PublicApiV1ReturnsListStatus: string
{
    case Requested = 'requested';
    case Approved = 'approved';
    case Received = 'received';
    case Refunded = 'refunded';
    case Rejected = 'rejected';
}
