<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Factuarea\Sdk\Models\Components;
class PublicApiV1RecurringInvoicesStatsResponseBody
{
    /**
     * Aggregated summary of the recurring invoices of the authenticated company: counters by status, upcoming due dates, current-month generation/failures, breakdown by frequency, upcoming runs and estimated revenue. Returned by `GET /v1/recurring_invoices/stats`.
     *
     * @var \Factuarea\Sdk\Models\Components\RecurringInvoiceStats $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\RecurringInvoiceStats')]
    public Components\RecurringInvoiceStats $data;

    /**
     * @param  \Factuarea\Sdk\Models\Components\RecurringInvoiceStats  $data
     * @phpstan-pure
     */
    public function __construct(Components\RecurringInvoiceStats $data)
    {
        $this->data = $data;
    }
}