<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Factuarea\Sdk\Models\Components;
class PublicApiV1StorefrontProductsShowResponseBody
{
    /**
     * The full sheet of an item of the shop window: the fourteen keys of its row plus its four collections —variants, presentations, option groups and gallery— so a product page can be painted with ONE read instead of five. The four collections carry exactly what the sub-collection operations return, so reading the sheet and reading its parts can never disagree.
     *
     * @var \Factuarea\Sdk\Models\Components\StorefrontProduct $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\StorefrontProduct')]
    public Components\StorefrontProduct $data;

    /**
     * @param  \Factuarea\Sdk\Models\Components\StorefrontProduct  $data
     * @phpstan-pure
     */
    public function __construct(Components\StorefrontProduct $data)
    {
        $this->data = $data;
    }
}