<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Brick\DateTime\LocalDate;
use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1SuppliersListRequest
{
    /**
     * Cursor for forward pagination. Use the `uuid` of the last object on the previous page.
     *
     * @var ?string $startingAfter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=starting_after')]
    public ?string $startingAfter = null;

    /**
     * Cursor for backward pagination. Use the `uuid` of the first object on the current page.
     *
     * @var ?string $endingBefore
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ending_before')]
    public ?string $endingBefore = null;

    /**
     * Fiscal tax number (NIF/CIF/NIE) of the supplier. Exact match on `tax_id`.
     *
     * @var ?string $taxId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tax_id')]
    public ?string $taxId = null;

    /**
     * Fiscal tax number (NIF/CIF/NIE) of the supplier. Comma-separated list. Any of the values matches.
     *
     * @var ?string $taxIdIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tax_id[in]')]
    public ?string $taxIdIn = null;

    /**
     * Fiscal tax number (NIF/CIF/NIE) of the supplier. Partial case-insensitive match (`LIKE %term%`) on `tax_id`.
     *
     * @var ?string $taxIdContains
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tax_id[contains]')]
    public ?string $taxIdContains = null;

    /**
     * Intra-community VAT number. Exact match on `vat_id`.
     *
     * @var ?string $vatId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vat_id')]
    public ?string $vatId = null;

    /**
     * Intra-community VAT number. Partial case-insensitive match (`LIKE %term%`) on `vat_id`.
     *
     * @var ?string $vatIdContains
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vat_id[contains]')]
    public ?string $vatIdContains = null;

    /**
     * Trade name of the supplier. Exact match on `name`.
     *
     * @var ?string $name
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=name')]
    public ?string $name = null;

    /**
     * Trade name of the supplier. Partial case-insensitive match (`LIKE %term%`) on `name`.
     *
     * @var ?string $nameContains
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=name[contains]')]
    public ?string $nameContains = null;

    /**
     * City of the supplier postal address. Exact match on `city`.
     *
     * @var ?string $city
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=city')]
    public ?string $city = null;

    /**
     * City of the supplier postal address. Partial case-insensitive match (`LIKE %term%`) on `city`.
     *
     * @var ?string $cityContains
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=city[contains]')]
    public ?string $cityContains = null;

    /**
     * Province / region of the supplier postal address. Exact match on `province`.
     *
     * @var ?string $province
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=province')]
    public ?string $province = null;

    /**
     * Province / region of the supplier postal address. Partial case-insensitive match (`LIKE %term%`) on `province`.
     *
     * @var ?string $provinceContains
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=province[contains]')]
    public ?string $provinceContains = null;

    /**
     * Filter by active / inactive suppliers. Exact match on `is_active`.
     *
     * @var ?bool $isActive
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=is_active')]
    public ?bool $isActive = null;

    /**
     * Creation date (ISO 8601). Greater than or equal to the given value.
     *
     * @var ?\DateTime $createdGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created[gte],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdGte = null;

    /**
     * Creation date (ISO 8601). Less than or equal to the given value.
     *
     * @var ?\DateTime $createdLte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created[lte],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdLte = null;

    /**
     * Creation date (ISO 8601). Strictly greater than the given value.
     *
     * @var ?\DateTime $createdGt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created[gt],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdGt = null;

    /**
     * Creation date (ISO 8601). Strictly less than the given value.
     *
     * @var ?\DateTime $createdLt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created[lt],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdLt = null;

    /**
     * Free-text search. Escaped `LIKE %term%` (case-insensitive, max 80 chars) across the resource's key text columns, combined with the other filters (AND) and compatible with the cursor.
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * Filter by metadata key/value pairs using the deepObject syntax `metadata[key]=value`. Multiple pairs are combined with AND. Each key must match `[A-Za-z0-9_.-]{1,64}`; a maximum of 50 pairs is allowed (more → 422).
     *
     * @var ?array<string, string> $metadata
     */
    #[SpeakeasyMetadata('queryParam:style=deepObject,explode=true,name=metadata')]
    public ?array $metadata = null;

    /**
     * Pin the API version (`YYYY-MM-DD`, Stripe-style date versioning) for this request; omit to use the key's pinned version, or the latest if none. Unsupported version → `400 unsupported_api_version`; malformed → `400 parameter_invalid_format`. The effective version is echoed in the `Factuarea-Version` response header. See the [Versioning guide](/guides/versioning).
     *
     * @var ?LocalDate $factuareaVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Factuarea-Version,dateTimeFormat=Y-m-d')]
    public ?LocalDate $factuareaVersion = null;

    /**
     * Operate on behalf of a child company (gestoría master key): pass its public `id` (UUID v7) and the request runs against that child's data without changing the key's scope, tier or environment (omit to use the key's own company). Invalid UUID → `400 parameter_invalid_uuid`; unknown or non-owned id → `404 profile_not_found`. See the [Acting on behalf guide](/guides/acting-on-behalf).
     *
     * @var ?string $xActiveProfile
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Active-Profile')]
    public ?string $xActiveProfile = null;

    /**
     * Number of objects to return. Integer between 1 and 100. Defaults to 25.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?int  $limit
     * @param  ?string  $startingAfter
     * @param  ?string  $endingBefore
     * @param  ?string  $taxId
     * @param  ?string  $taxIdIn
     * @param  ?string  $taxIdContains
     * @param  ?string  $vatId
     * @param  ?string  $vatIdContains
     * @param  ?string  $name
     * @param  ?string  $nameContains
     * @param  ?string  $city
     * @param  ?string  $cityContains
     * @param  ?string  $province
     * @param  ?string  $provinceContains
     * @param  ?bool  $isActive
     * @param  ?\DateTime  $createdGte
     * @param  ?\DateTime  $createdLte
     * @param  ?\DateTime  $createdGt
     * @param  ?\DateTime  $createdLt
     * @param  ?string  $search
     * @param  ?array<string, string>  $metadata
     * @param  ?LocalDate  $factuareaVersion
     * @param  ?string  $xActiveProfile
     * @phpstan-pure
     */
    public function __construct(?string $startingAfter = null, ?string $endingBefore = null, ?string $taxId = null, ?string $taxIdIn = null, ?string $taxIdContains = null, ?string $vatId = null, ?string $vatIdContains = null, ?string $name = null, ?string $nameContains = null, ?string $city = null, ?string $cityContains = null, ?string $province = null, ?string $provinceContains = null, ?bool $isActive = null, ?\DateTime $createdGte = null, ?\DateTime $createdLte = null, ?\DateTime $createdGt = null, ?\DateTime $createdLt = null, ?string $search = null, ?array $metadata = null, ?LocalDate $factuareaVersion = null, ?string $xActiveProfile = null, ?int $limit = 25)
    {
        $this->startingAfter = $startingAfter;
        $this->endingBefore = $endingBefore;
        $this->taxId = $taxId;
        $this->taxIdIn = $taxIdIn;
        $this->taxIdContains = $taxIdContains;
        $this->vatId = $vatId;
        $this->vatIdContains = $vatIdContains;
        $this->name = $name;
        $this->nameContains = $nameContains;
        $this->city = $city;
        $this->cityContains = $cityContains;
        $this->province = $province;
        $this->provinceContains = $provinceContains;
        $this->isActive = $isActive;
        $this->createdGte = $createdGte;
        $this->createdLte = $createdLte;
        $this->createdGt = $createdGt;
        $this->createdLt = $createdLt;
        $this->search = $search;
        $this->metadata = $metadata;
        $this->factuareaVersion = $factuareaVersion;
        $this->xActiveProfile = $xActiveProfile;
        $this->limit = $limit;
    }
}