<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;


class PublicApiV1DeliveryNotesSendResponseBody
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Operations\PublicApiV1DeliveryNotesSendData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Operations\PublicApiV1DeliveryNotesSendData')]
    public PublicApiV1DeliveryNotesSendData $data;

    /**
     * @param  \Factuarea\Sdk\Models\Operations\PublicApiV1DeliveryNotesSendData  $data
     * @phpstan-pure
     */
    public function __construct(PublicApiV1DeliveryNotesSendData $data)
    {
        $this->data = $data;
    }
}