<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Brick\DateTime\LocalDate;
use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1AbsencePoliciesShowRequest
{
    /**
     * Public identifier (UUID v7) of the company. Get it from `GET /v1/me` (`data.scope[].id`).
     *
     * @var string $company
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public string $company;

    /**
     * Public identifier (UUID v7) of the absence policy.
     *
     * @var string $absencePolicy
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=absence_policy')]
    public string $absencePolicy;

    /**
     * Pin the API version (`YYYY-MM-DD`, Stripe-style date versioning) for this request; omit to use the key's pinned version, or the latest if none. Unsupported version → `400 unsupported_api_version`; malformed → `400 parameter_invalid_format`. The effective version is echoed in the `Factuarea-Version` response header. See the [Versioning guide](/guides/versioning).
     *
     * @var ?LocalDate $factuareaVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Factuarea-Version,dateTimeFormat=Y-m-d')]
    public ?LocalDate $factuareaVersion = null;

    /**
     * @param  string  $company
     * @param  string  $absencePolicy
     * @param  ?LocalDate  $factuareaVersion
     * @phpstan-pure
     */
    public function __construct(string $company, string $absencePolicy, ?LocalDate $factuareaVersion = null)
    {
        $this->company = $company;
        $this->absencePolicy = $absencePolicy;
        $this->factuareaVersion = $factuareaVersion;
    }
}