<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1RecurringInvoicesLogsRequest
{
    /**
     *
     * @var string $recurringInvoice
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=recurring_invoice')]
    public string $recurringInvoice;

    /**
     * Default `'25'` (string) por consistencia OpenAPI/Spectral.
     *
     * @var ?string $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?string $limit = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?string $perPage
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=per_page')]
    public ?string $perPage = null;

    /**
     * @param  string  $recurringInvoice
     * @param  ?string  $perPage
     * @param  ?string  $limit
     * @param  ?string  $cursor
     * @phpstan-pure
     */
    public function __construct(string $recurringInvoice, ?string $limit = null, ?string $cursor = null, ?string $perPage = '25')
    {
        $this->recurringInvoice = $recurringInvoice;
        $this->limit = $limit;
        $this->cursor = $cursor;
        $this->perPage = $perPage;
    }
}