<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;


class PublicApiV1TasksEntityLinksDeleteResponseBody
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Operations\PublicApiV1TasksEntityLinksDeleteData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Operations\PublicApiV1TasksEntityLinksDeleteData')]
    public PublicApiV1TasksEntityLinksDeleteData $data;

    /**
     * @param  \Factuarea\Sdk\Models\Operations\PublicApiV1TasksEntityLinksDeleteData  $data
     * @phpstan-pure
     */
    public function __construct(PublicApiV1TasksEntityLinksDeleteData $data)
    {
        $this->data = $data;
    }
}