<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Brick\DateTime\LocalDate;
use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1StoresProductLinksListRequest
{
    /**
     *
     * @var string $company
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public string $company;

    /**
     *
     * @var string $store
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=store')]
    public string $store;

    /**
     * Public ID of your own product. A product that does not exist in your company is rejected exactly like one from another company. Exact match on `product_id`.
     *
     * @var ?string $productId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=product_id')]
    public ?string $productId = null;

    /**
     * Cursor for forward pagination: the `id` of the last of the links on the previous page. This listing moves FORWARD only — there is no `ending_before` — so keep the cursor of the page you want to resume from. A malformed cursor returns 400.
     *
     * @var ?string $startingAfter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=starting_after')]
    public ?string $startingAfter = null;

    /**
     * Link status written by the outbound rail: `pending` is claimed with no remote counterpart sealed yet, `linked` is sealed and publishing, `conflict` is ambiguous and does not publish until resolved. Exact match on `status`.
     *
     * @var ?\Factuarea\Sdk\Models\Operations\PublicApiV1StoresProductLinksListStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?PublicApiV1StoresProductLinksListStatus $status = null;

    /**
     * Remote product identity, exactly as the store returns it (up to 191 characters). Exact match on `external_product_id`.
     *
     * @var ?string $externalProductId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_product_id')]
    public ?string $externalProductId = null;

    /**
     * Remote variant identity, exactly as the store returns it (up to 191 characters). Exact match on `external_variant_id`.
     *
     * @var ?string $externalVariantId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_variant_id')]
    public ?string $externalVariantId = null;

    /**
     * Remote inventory item identity (a store may keep it apart from the variant), up to 191 characters. Exact match on `external_inventory_item_id`.
     *
     * @var ?string $externalInventoryItemId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_inventory_item_id')]
    public ?string $externalInventoryItemId = null;

    /**
     * Pin the API version (`YYYY-MM-DD`, Stripe-style date versioning) for this request; omit to use the key's pinned version, or the latest if none. Unsupported version → `400 unsupported_api_version`; malformed → `400 parameter_invalid_format`. The effective version is echoed in the `Factuarea-Version` response header. See the [Versioning guide](/guides/versioning).
     *
     * @var ?LocalDate $factuareaVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Factuarea-Version,dateTimeFormat=Y-m-d')]
    public ?LocalDate $factuareaVersion = null;

    /**
     * Operate on behalf of a child company (gestoría master key): pass its public `id` (UUID v7) and the request runs against that child's data without changing the key's scope, tier or environment (omit to use the key's own company). Invalid UUID → `400 parameter_invalid_uuid`; unknown or non-owned id → `404 profile_not_found`. See the [Acting on behalf guide](/guides/acting-on-behalf).
     *
     * @var ?string $xActiveProfile
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Active-Profile')]
    public ?string $xActiveProfile = null;

    /**
     * Number of links to return. Integer between 1 and 100. Defaults to 25. A non-integer or out-of-range value returns 400.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  string  $company
     * @param  string  $store
     * @param  ?string  $productId
     * @param  ?int  $limit
     * @param  ?string  $startingAfter
     * @param  ?\Factuarea\Sdk\Models\Operations\PublicApiV1StoresProductLinksListStatus  $status
     * @param  ?string  $externalProductId
     * @param  ?string  $externalVariantId
     * @param  ?string  $externalInventoryItemId
     * @param  ?LocalDate  $factuareaVersion
     * @param  ?string  $xActiveProfile
     * @phpstan-pure
     */
    public function __construct(string $company, string $store, ?string $productId = null, ?string $startingAfter = null, ?PublicApiV1StoresProductLinksListStatus $status = null, ?string $externalProductId = null, ?string $externalVariantId = null, ?string $externalInventoryItemId = null, ?LocalDate $factuareaVersion = null, ?string $xActiveProfile = null, ?int $limit = 25)
    {
        $this->company = $company;
        $this->store = $store;
        $this->productId = $productId;
        $this->startingAfter = $startingAfter;
        $this->status = $status;
        $this->externalProductId = $externalProductId;
        $this->externalVariantId = $externalVariantId;
        $this->externalInventoryItemId = $externalInventoryItemId;
        $this->factuareaVersion = $factuareaVersion;
        $this->xActiveProfile = $xActiveProfile;
        $this->limit = $limit;
    }
}