<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Brick\DateTime\LocalDate;
use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1InvoicesPdfRequest
{
    /**
     * Public identifier (UUID v7) of the company. Get it from `GET /v1/me` (`data.scope[].id`).
     *
     * @var string $company
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public string $company;

    /**
     * Public identifier (UUID v7) of the invoice.
     *
     * @var string $invoice
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=invoice')]
    public string $invoice;

    /**
     * Send `1` to get the PDF as an attachment (`Content-Disposition: attachment`) instead of inline.
     *
     * @var ?string $download
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=download')]
    public ?string $download = null;

    /**
     * Pin the API version (`YYYY-MM-DD`, Stripe-style date versioning) for this request; omit to use the key's pinned version, or the latest if none. Unsupported version → `400 unsupported_api_version`; malformed → `400 parameter_invalid_format`. The effective version is echoed in the `Factuarea-Version` response header. See the [Versioning guide](/guides/versioning).
     *
     * @var ?LocalDate $factuareaVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Factuarea-Version,dateTimeFormat=Y-m-d')]
    public ?LocalDate $factuareaVersion = null;

    /**
     * @param  string  $company
     * @param  string  $invoice
     * @param  ?string  $download
     * @param  ?LocalDate  $factuareaVersion
     * @phpstan-pure
     */
    public function __construct(string $company, string $invoice, ?string $download = null, ?LocalDate $factuareaVersion = null)
    {
        $this->company = $company;
        $this->invoice = $invoice;
        $this->download = $download;
        $this->factuareaVersion = $factuareaVersion;
    }
}