<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Brick\DateTime\LocalDate;
use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1StockTransfersListRequest
{
    /**
     *
     * @var string $company
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public string $company;

    /**
     * Cursor for forward pagination. Use the `uuid` of the last object on the previous page.
     *
     * @var ?string $startingAfter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=starting_after')]
    public ?string $startingAfter = null;

    /**
     * Cursor for backward pagination. Use the `uuid` of the first object on the current page.
     *
     * @var ?string $endingBefore
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ending_before')]
    public ?string $endingBefore = null;

    /**
     * Stock transfer status. Four published values: `draft` (being written, it moves no stock), `dispatched` (the goods left the origin warehouse and are in transit), `received` (they arrived in full at the destination) and `cancelled` (terminal). A partially received transfer stays `dispatched` until the last unit arrives. Exact match on `status`.
     *
     * @var ?\Factuarea\Sdk\Models\Operations\PublicApiV1StockTransfersListStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?PublicApiV1StockTransfersListStatus $status = null;

    /**
     * Stock transfer status. Four published values: `draft` (being written, it moves no stock), `dispatched` (the goods left the origin warehouse and are in transit), `received` (they arrived in full at the destination) and `cancelled` (terminal). A partially received transfer stays `dispatched` until the last unit arrives. Comma-separated list. Any of the values matches.
     *
     * @var ?string $statusIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status[in]')]
    public ?string $statusIn = null;

    /**
     * Public ID of the warehouse the goods leave from. A warehouse that does not belong to the company in the path yields an EMPTY page, never a rejection; a value that is not a public ID at all is rejected, because it cannot be anybody's warehouse. Exact match on `origin_warehouse_id`.
     *
     * @var ?string $originWarehouseId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=origin_warehouse_id')]
    public ?string $originWarehouseId = null;

    /**
     * Public ID of the warehouse the goods leave from. A warehouse that does not belong to the company in the path yields an EMPTY page, never a rejection; a value that is not a public ID at all is rejected, because it cannot be anybody's warehouse. Comma-separated list. Any of the values matches.
     *
     * @var ?string $originWarehouseIdIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=origin_warehouse_id[in]')]
    public ?string $originWarehouseIdIn = null;

    /**
     * Public ID of the warehouse that receives the goods, with the same rules as the origin one. Exact match on `destination_warehouse_id`.
     *
     * @var ?string $destinationWarehouseId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=destination_warehouse_id')]
    public ?string $destinationWarehouseId = null;

    /**
     * Public ID of the warehouse that receives the goods, with the same rules as the origin one. Comma-separated list. Any of the values matches.
     *
     * @var ?string $destinationWarehouseIdIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=destination_warehouse_id[in]')]
    public ?string $destinationWarehouseIdIn = null;

    /**
     * Transfer number, stamped when the transfer is created and unique per company. It is not a fiscal number and its sequence is not dense. Exact match only: use `search` for partial matching. Exact match on `number`.
     *
     * @var ?string $number
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=number')]
    public ?string $number = null;

    /**
     * Transfer number, stamped when the transfer is created and unique per company. It is not a fiscal number and its sequence is not dense. Exact match only: use `search` for partial matching. Comma-separated list. Any of the values matches.
     *
     * @var ?string $numberIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=number[in]')]
    public ?string $numberIn = null;

    /**
     * Moment the goods left the origin warehouse (ISO 8601). A bare day (`2026-03-10`) means the WHOLE of that day, not its first instant, so a transfer dispatched at 09:30 matches it. A transfer still in draft never matches this filter. Exact match on `dispatched_at`.
     *
     * @var ?\DateTime $dispatchedAt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=dispatched_at,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $dispatchedAt = null;

    /**
     * Moment the goods left the origin warehouse (ISO 8601). A bare day (`2026-03-10`) means the WHOLE of that day, not its first instant, so a transfer dispatched at 09:30 matches it. A transfer still in draft never matches this filter. Greater than or equal to the given value.
     *
     * @var ?\DateTime $dispatchedAtGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=dispatched_at[gte],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $dispatchedAtGte = null;

    /**
     * Moment the goods left the origin warehouse (ISO 8601). A bare day (`2026-03-10`) means the WHOLE of that day, not its first instant, so a transfer dispatched at 09:30 matches it. A transfer still in draft never matches this filter. Less than or equal to the given value.
     *
     * @var ?\DateTime $dispatchedAtLte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=dispatched_at[lte],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $dispatchedAtLte = null;

    /**
     * Moment the goods left the origin warehouse (ISO 8601). A bare day (`2026-03-10`) means the WHOLE of that day, not its first instant, so a transfer dispatched at 09:30 matches it. A transfer still in draft never matches this filter. Strictly greater than the given value.
     *
     * @var ?\DateTime $dispatchedAtGt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=dispatched_at[gt],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $dispatchedAtGt = null;

    /**
     * Moment the goods left the origin warehouse (ISO 8601). A bare day (`2026-03-10`) means the WHOLE of that day, not its first instant, so a transfer dispatched at 09:30 matches it. A transfer still in draft never matches this filter. Strictly less than the given value.
     *
     * @var ?\DateTime $dispatchedAtLt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=dispatched_at[lt],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $dispatchedAtLt = null;

    /**
     * Moment the transfer was received IN FULL (ISO 8601), with the same day semantics as the dispatch one. A partially received transfer has no value here yet, so it never matches this filter. Exact match on `received_at`.
     *
     * @var ?\DateTime $receivedAt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=received_at,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $receivedAt = null;

    /**
     * Moment the transfer was received IN FULL (ISO 8601), with the same day semantics as the dispatch one. A partially received transfer has no value here yet, so it never matches this filter. Greater than or equal to the given value.
     *
     * @var ?\DateTime $receivedAtGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=received_at[gte],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $receivedAtGte = null;

    /**
     * Moment the transfer was received IN FULL (ISO 8601), with the same day semantics as the dispatch one. A partially received transfer has no value here yet, so it never matches this filter. Less than or equal to the given value.
     *
     * @var ?\DateTime $receivedAtLte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=received_at[lte],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $receivedAtLte = null;

    /**
     * Moment the transfer was received IN FULL (ISO 8601), with the same day semantics as the dispatch one. A partially received transfer has no value here yet, so it never matches this filter. Strictly greater than the given value.
     *
     * @var ?\DateTime $receivedAtGt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=received_at[gt],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $receivedAtGt = null;

    /**
     * Moment the transfer was received IN FULL (ISO 8601), with the same day semantics as the dispatch one. A partially received transfer has no value here yet, so it never matches this filter. Strictly less than the given value.
     *
     * @var ?\DateTime $receivedAtLt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=received_at[lt],dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $receivedAtLt = null;

    /**
     * Sort order. Use a field for ascending or a `-` prefix for descending (e.g. `-created`). Allowed fields: `created`, `number`, `dispatched_at`. Combined with the cursor, ordering stays deterministic (a stable secondary sort by the cursor id, Stripe-style). When omitted, results follow the default cursor order (`created` descending).
     *
     * @var ?\Factuarea\Sdk\Models\Operations\PublicApiV1StockTransfersListSort $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?PublicApiV1StockTransfersListSort $sort = null;

    /**
     * Free-text search. Escaped `LIKE %term%` (case-insensitive, max 80 chars) across the resource's key text columns, combined with the other filters (AND) and compatible with the cursor.
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * Pin the API version (`YYYY-MM-DD`, Stripe-style date versioning) for this request; omit to use the key's pinned version, or the latest if none. Unsupported version → `400 unsupported_api_version`; malformed → `400 parameter_invalid_format`. The effective version is echoed in the `Factuarea-Version` response header. See the [Versioning guide](/guides/versioning).
     *
     * @var ?LocalDate $factuareaVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Factuarea-Version,dateTimeFormat=Y-m-d')]
    public ?LocalDate $factuareaVersion = null;

    /**
     * Operate on behalf of a child company (gestoría master key): pass its public `id` (UUID v7) and the request runs against that child's data without changing the key's scope, tier or environment (omit to use the key's own company). Invalid UUID → `400 parameter_invalid_uuid`; unknown or non-owned id → `404 profile_not_found`. See the [Acting on behalf guide](/guides/acting-on-behalf).
     *
     * @var ?string $xActiveProfile
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Active-Profile')]
    public ?string $xActiveProfile = null;

    /**
     * Number of objects to return. Integer between 1 and 100. Defaults to 25.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  string  $company
     * @param  ?int  $limit
     * @param  ?string  $startingAfter
     * @param  ?string  $endingBefore
     * @param  ?\Factuarea\Sdk\Models\Operations\PublicApiV1StockTransfersListStatus  $status
     * @param  ?string  $statusIn
     * @param  ?string  $originWarehouseId
     * @param  ?string  $originWarehouseIdIn
     * @param  ?string  $destinationWarehouseId
     * @param  ?string  $destinationWarehouseIdIn
     * @param  ?string  $number
     * @param  ?string  $numberIn
     * @param  ?\DateTime  $dispatchedAt
     * @param  ?\DateTime  $dispatchedAtGte
     * @param  ?\DateTime  $dispatchedAtLte
     * @param  ?\DateTime  $dispatchedAtGt
     * @param  ?\DateTime  $dispatchedAtLt
     * @param  ?\DateTime  $receivedAt
     * @param  ?\DateTime  $receivedAtGte
     * @param  ?\DateTime  $receivedAtLte
     * @param  ?\DateTime  $receivedAtGt
     * @param  ?\DateTime  $receivedAtLt
     * @param  ?\Factuarea\Sdk\Models\Operations\PublicApiV1StockTransfersListSort  $sort
     * @param  ?string  $search
     * @param  ?LocalDate  $factuareaVersion
     * @param  ?string  $xActiveProfile
     * @phpstan-pure
     */
    public function __construct(string $company, ?string $startingAfter = null, ?string $endingBefore = null, ?PublicApiV1StockTransfersListStatus $status = null, ?string $statusIn = null, ?string $originWarehouseId = null, ?string $originWarehouseIdIn = null, ?string $destinationWarehouseId = null, ?string $destinationWarehouseIdIn = null, ?string $number = null, ?string $numberIn = null, ?\DateTime $dispatchedAt = null, ?\DateTime $dispatchedAtGte = null, ?\DateTime $dispatchedAtLte = null, ?\DateTime $dispatchedAtGt = null, ?\DateTime $dispatchedAtLt = null, ?\DateTime $receivedAt = null, ?\DateTime $receivedAtGte = null, ?\DateTime $receivedAtLte = null, ?\DateTime $receivedAtGt = null, ?\DateTime $receivedAtLt = null, ?PublicApiV1StockTransfersListSort $sort = null, ?string $search = null, ?LocalDate $factuareaVersion = null, ?string $xActiveProfile = null, ?int $limit = 25)
    {
        $this->company = $company;
        $this->startingAfter = $startingAfter;
        $this->endingBefore = $endingBefore;
        $this->status = $status;
        $this->statusIn = $statusIn;
        $this->originWarehouseId = $originWarehouseId;
        $this->originWarehouseIdIn = $originWarehouseIdIn;
        $this->destinationWarehouseId = $destinationWarehouseId;
        $this->destinationWarehouseIdIn = $destinationWarehouseIdIn;
        $this->number = $number;
        $this->numberIn = $numberIn;
        $this->dispatchedAt = $dispatchedAt;
        $this->dispatchedAtGte = $dispatchedAtGte;
        $this->dispatchedAtLte = $dispatchedAtLte;
        $this->dispatchedAtGt = $dispatchedAtGt;
        $this->dispatchedAtLt = $dispatchedAtLt;
        $this->receivedAt = $receivedAt;
        $this->receivedAtGte = $receivedAtGte;
        $this->receivedAtLte = $receivedAtLte;
        $this->receivedAtGt = $receivedAtGt;
        $this->receivedAtLt = $receivedAtLt;
        $this->sort = $sort;
        $this->search = $search;
        $this->factuareaVersion = $factuareaVersion;
        $this->xActiveProfile = $xActiveProfile;
        $this->limit = $limit;
    }
}