<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Factuarea\Sdk\Models\Components;
class PublicApiV1ProjectsCustomFieldsCreateResponseBody
{
    /**
     * A custom field defined for the tasks of a project.
     *
     * @var \Factuarea\Sdk\Models\Components\ProjectCustomField $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\ProjectCustomField')]
    public Components\ProjectCustomField $data;

    /**
     * @param  \Factuarea\Sdk\Models\Components\ProjectCustomField  $data
     * @phpstan-pure
     */
    public function __construct(Components\ProjectCustomField $data)
    {
        $this->data = $data;
    }
}