<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;

use Brick\DateTime\LocalDate;
use Factuarea\Sdk\Models\Components;
use Factuarea\Sdk\Utils\SpeakeasyMetadata;
class PublicApiV1ProformasRejectRequest
{
    /**
     * Public identifier (UUID) of the company the request acts on. It must be in your credential's scope; read it from `GET /v1/me` (`data.scope[].id`). Never the tax ID.
     *
     * @var string $company
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public string $company;

    /**
     * Public identifier (UUID v7) of the proforma, as returned in `id` by its list and detail responses.
     *
     * @var string $proforma
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=proforma')]
    public string $proforma;

    /**
     * Client-generated opaque key (up to 255 characters; UUID v7 recommended) that makes retries safe: the first response is cached and replayed for repeats without re-executing the mutation. Reusing a key with a different body returns `422 idempotency_key_reused`. See the [Idempotency guide](/guides/idempotency).
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public ?string $idempotencyKey = null;

    /**
     * Pin the API version (`YYYY-MM-DD`, Stripe-style date versioning) for this request; omit to use the key's pinned version, or the latest if none. Unsupported version → `400 unsupported_api_version`; malformed → `400 parameter_invalid_format`. The effective version is echoed in the `Factuarea-Version` response header. See the [Versioning guide](/guides/versioning).
     *
     * @var ?LocalDate $factuareaVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Factuarea-Version,dateTimeFormat=Y-m-d')]
    public ?LocalDate $factuareaVersion = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\RejectProformaRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Components\RejectProformaRequest $body = null;

    /**
     * @param  string  $company
     * @param  string  $proforma
     * @param  ?string  $idempotencyKey
     * @param  ?LocalDate  $factuareaVersion
     * @param  ?\Factuarea\Sdk\Models\Components\RejectProformaRequest  $body
     * @phpstan-pure
     */
    public function __construct(string $company, string $proforma, ?string $idempotencyKey = null, ?LocalDate $factuareaVersion = null, ?Components\RejectProformaRequest $body = null)
    {
        $this->company = $company;
        $this->proforma = $proforma;
        $this->idempotencyKey = $idempotencyKey;
        $this->factuareaVersion = $factuareaVersion;
        $this->body = $body;
    }
}