<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Operations;


/** Remission mode of the company AFTER registering: registering a representation moves a company that remits through a third-party mode to the mode of the new kind (or back to `own_certificate` when that mode cannot be used); with `own_certificate` it does not change. */
enum RemissionMode: string
{
    case OwnCertificate = 'own_certificate';
    case SocialCollaborator = 'social_collaborator';
    case PowerOfAttorney = 'power_of_attorney';
}
