<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** BulkStatusInvoicesV1Request - Transition several invoices to `new_status` (`issued` or `paid`) in one request, up to 50 per batch. `issued` issues each draft without sending any email; `sent` is still accepted as an alias of `issued` in every API version and never marks the invoice as delivered. `ids` is an array of invoice UUIDs; `payment_date` is required and cannot be in the future when `new_status` is `paid`. Every transition passes the document state guard, and invoices that cannot transition are returned under `failures[]`. */
class BulkStatusInvoicesV1Request
{
    /**
     * $ids
     *
     * @var array<string> $ids
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $ids;

    /**
     * Target status: `issued` issues each draft (definitive number, VeriFactu record) without sending any email; `paid` records a payment for the outstanding amount of each issued invoice. `sent` is accepted as an alias of `issued` in every API version and never sets the delivery mark (`is_sent`).
     *
     * @var \Factuarea\Sdk\Models\Components\BulkStatusInvoicesV1RequestNewStatus $newStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\BulkStatusInvoicesV1RequestNewStatus')]
    public BulkStatusInvoicesV1RequestNewStatus $newStatus;

    /**
     *
     * @var ?\DateTime $paymentDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $paymentDate = null;

    /**
     * @param  array<string>  $ids
     * @param  \Factuarea\Sdk\Models\Components\BulkStatusInvoicesV1RequestNewStatus  $newStatus
     * @param  ?\DateTime  $paymentDate
     * @phpstan-pure
     */
    public function __construct(array $ids, BulkStatusInvoicesV1RequestNewStatus $newStatus, ?\DateTime $paymentDate = null)
    {
        $this->ids = $ids;
        $this->newStatus = $newStatus;
        $this->paymentDate = $paymentDate;
    }
}