<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Target status of the transition: `confirmed`, `cancelled` or `closed`. Those three are the only ones that can be requested — the four consumption states are derived from delivery notes and invoices, and `draft` is never a target. */
enum BulkStatusSalesOrdersRequestNewStatus: string
{
    case Confirmed = 'confirmed';
    case Cancelled = 'cancelled';
    case Closed = 'closed';
}
