<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


enum BusinessContactImportPreviewAction: string
{
    case Create = 'create';
    case Update = 'update';
    case AddRole = 'add_role';
    case MergeCandidate = 'merge_candidate';
    case Conflict = 'conflict';
    case Invalid = 'invalid';
}
