<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/**
 * CalculateTaxRequest - Public REST API v1 — POST /v1/taxes/calculate.
 *
 *
 * Body: `{ base: float, taxes_id: string }`. `taxes_id` es la FK a la tabla
 * global `taxes` (valor UUID v7) — plural (D1), NUNCA `tax_id` (NIF/CIF fiscal).
 * Devuelve `{ base, tax_rate, tax_amount, total_amount, tax }`.
 */
class CalculateTaxRequest
{
    /**
     *
     * @var float $base
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('base')]
    public float $base;

    /**
     * NOTE: no `exists:taxes,uuid` rule here. Existence is resolved by the
     *
     * Controller via `resolveUuid(TaxModel::class)`, which throws
     * `TaxNotFoundException` (404 `tax_not_found`) for a well-formed but
     * non-existent uuid — via `PublicApiNotFoundExceptionRegistry`. With
     * `exists` the FormRequest would emit 422 `invalid_param_value` and the
     * canonical 404 would never be reached. The `uuid` rule keeps the 422 for
     * malformed uuids (arbitrary text is not passed to the database lookup).
     *
     * @var string $taxesId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxes_id')]
    public string $taxesId;

    /**
     * @param  float  $base
     * @param  string  $taxesId
     * @phpstan-pure
     */
    public function __construct(float $base, string $taxesId)
    {
        $this->base = $base;
        $this->taxesId = $taxesId;
    }
}