<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class ConditionTrace
{
    /**
     * Path of the evaluated field inside the `data.object` of the sample event.
     *
     * @var string $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    public string $path;

    /**
     * Operator that was applied.
     *
     * @var \Factuarea\Sdk\Models\Components\AutomationDryRunOperator $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\AutomationDryRunOperator')]
    public AutomationDryRunOperator $operator;

    /**
     * Comparison value declared by the condition. Its shape follows the `value_shape` of the operator: a scalar, an array of scalars, or `null` for operators that take no value.
     *
     * @var mixed $expected
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expected')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $expected;

    /**
     * Value actually found at `path` in the sample payload, or `null` when the field was absent.
     *
     * @var mixed $observed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('observed')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $observed;

    /**
     * Whether this leaf was satisfied.
     *
     * @var bool $matched
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('matched')]
    public bool $matched;

    /**
     * @param  string  $path
     * @param  \Factuarea\Sdk\Models\Components\AutomationDryRunOperator  $operator
     * @param  mixed  $expected
     * @param  mixed  $observed
     * @param  bool  $matched
     * @phpstan-pure
     */
    public function __construct(string $path, AutomationDryRunOperator $operator, mixed $expected, mixed $observed, bool $matched)
    {
        $this->path = $path;
        $this->operator = $operator;
        $this->expected = $expected;
        $this->observed = $observed;
        $this->matched = $matched;
    }
}