<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;

use Brick\DateTime\LocalDate;
class CreateEmployeeRequest
{
    /**
     * Employee first name.
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    public string $firstName;

    /**
     * Employee last name.
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    public string $lastName;

    /**
     * Employee email (unique within the company).
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     * Working-hours arrangement: `full_time` or `part_time`.
     *
     * @var \Factuarea\Sdk\Models\Components\CreateEmployeeRequestEmploymentType $employmentType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employment_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateEmployeeRequestEmploymentType')]
    public CreateEmployeeRequestEmploymentType $employmentType;

    /**
     * Weekly contracted hours (greater than 0 and up to 168).
     *
     * @var float $contractHours
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contract_hours')]
    public float $contractHours;

    /**
     * Employee hire date, in `Y-m-d`.
     *
     * @var LocalDate $hireDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hire_date')]
    public LocalDate $hireDate;

    /**
     * Spanish autonomous community or city (ISO 3166-2:ES) used to localise public holidays.
     *
     * @var \Factuarea\Sdk\Models\Components\CreateEmployeeRequestCcaa $ccaa
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ccaa')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateEmployeeRequestCcaa')]
    public CreateEmployeeRequestCcaa $ccaa;

    /**
     * Spanish fiscal identifier (NIF/NIE) of the employee (optional).
     *
     * @var ?string $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxId = null;

    /**
     * Role or position of the employee (optional).
     *
     * @var ?string $jobTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job_title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jobTitle = null;

    /**
     * External integration key (ERP/CRM), unique per company
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     * A free map of up to 50 key→value pairs for storing arbitrary structured data (values are strings up to 500 characters). Unlike `custom_fields` — an ordered list of typed `{field, value}` pairs with display semantics, present on the six document resources — `metadata` is an unordered map for opaque integration data; a document may carry both. The master resources (Client, Supplier) have no `custom_fields`, so their `metadata` doubles as the custom-fields store.
     *
     *
     * **Reserved keys (read-only).** When the system auto-issues an invoice from a payment correlation (Stripe/GoCardless/MONEI), it writes `stripe_subscription_id`, `stripe_invoice_id`, `billing_reason`, `period_start` and `period_end` into that invoice metadata automatically. Do not set or overwrite them by hand — the platform owns them and a manual value may be replaced when the correlation runs.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $email
     * @param  \Factuarea\Sdk\Models\Components\CreateEmployeeRequestEmploymentType  $employmentType
     * @param  float  $contractHours
     * @param  LocalDate  $hireDate
     * @param  \Factuarea\Sdk\Models\Components\CreateEmployeeRequestCcaa  $ccaa
     * @param  ?string  $taxId
     * @param  ?string  $jobTitle
     * @param  ?string  $externalId
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $email, CreateEmployeeRequestEmploymentType $employmentType, float $contractHours, LocalDate $hireDate, CreateEmployeeRequestCcaa $ccaa, ?string $taxId = null, ?string $jobTitle = null, ?string $externalId = null, ?array $metadata = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->employmentType = $employmentType;
        $this->contractHours = $contractHours;
        $this->hireDate = $hireDate;
        $this->ccaa = $ccaa;
        $this->taxId = $taxId;
        $this->jobTitle = $jobTitle;
        $this->externalId = $externalId;
        $this->metadata = $metadata;
    }
}