<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** CreateProductRequest - Create a product in your catalog. Required: `name` and `price`. Optional: `sku` (unique per company), `description`, `tags`, `stock` (initial quantity), `low_stock_threshold`, `manage_stock`, `currency` (`EUR` only — any other code returns 422), `tax_rate_id`, `is_active`, `metadata` and `external_id`. Stock changes after creation are made through `PATCH /v1/companies/{company}/products/{product}/stock`, not through this endpoint. */
class CreateProductRequest
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    public string $price;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\CreateProductRequestItemKind $itemKind
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('item_kind')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateProductRequestItemKind|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateProductRequestItemKind $itemKind = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\CreateProductRequestBaseUnit $baseUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('base_unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateProductRequestBaseUnit|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateProductRequestBaseUnit $baseUnit = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\CreateProductRequestCatalogAvailabilityMode $catalogAvailabilityMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('catalog_availability_mode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateProductRequestCatalogAvailabilityMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateProductRequestCatalogAvailabilityMode $catalogAvailabilityMode = null;

    /**
     * Stock keeping unit (your own product code), unique per company. Optional; up to 100 characters.
     *
     * @var ?string $sku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sku')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sku = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * $tags
     *
     * @var ?array<string> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     * $specifications
     *
     * @var ?array<?string> $specifications
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('specifications')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string|null>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $specifications = null;

    /**
     * Initial stock. Absent → defaults to 0. Later you can set it absolutely with `stock` on `PATCH /v1/companies/{company}/products/{uuid}`, or move it with `PATCH /v1/companies/{company}/products/{uuid}/stock` (`set`/`increase`/`decrease`).
     *
     * @var ?float $stock
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stock')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $stock = null;

    /**
     *
     * @var ?float $lowStockThreshold
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('low_stock_threshold')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $lowStockThreshold = null;

    /**
     * Whether this product takes part in document-driven stock movements: with `true`, issuing or receiving a document that includes it moves its stock automatically and the movement is recorded in the stock ledger. It only takes effect if your company also has stock management enabled; absent or `null` means `false`.
     *
     * @var ?bool $manageStock
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manage_stock')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $manageStock = null;

    /**
     * Product amounts are read-only EUR: only `EUR` (or absence/null) is accepted.
     *
     * @var ?\Factuarea\Sdk\Models\Components\CreateProductRequestCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateProductRequestCurrency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateProductRequestCurrency $currency = null;

    /**
     *
     * @var ?string $taxRateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxRateId = null;

    /**
     *
     * @var ?bool $isActive
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_active')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isActive = null;

    /**
     * A free map of up to 50 key→value pairs for storing arbitrary structured data (values are strings up to 500 characters). Unlike `custom_fields` — an ordered list of typed `{field, value}` pairs with display semantics, present on the six document resources — `metadata` is an unordered map for opaque integration data; a document may carry both. The master resources (Client, Supplier) have no `custom_fields`, so their `metadata` doubles as the custom-fields store.
     *
     *
     * **Reserved keys (read-only).** When the system auto-issues an invoice from a payment correlation (Stripe/GoCardless/MONEI), it writes `stripe_subscription_id`, `stripe_invoice_id`, `billing_reason`, `period_start` and `period_end` into that invoice metadata automatically. Do not set or overwrite them by hand — the platform owns them and a manual value may be replaced when the correlation runs.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Third-party integration key from your ERP/CRM (orthogonal to `sku`). Free-form, up to 100 characters.
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     * $optionGroups
     *
     * @var ?array<\Factuarea\Sdk\Models\Components\CreateProductRequestOptionGroup> $optionGroups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('option_groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\CreateProductRequestOptionGroup>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $optionGroups = null;

    /**
     * $configurations
     *
     * @var ?array<\Factuarea\Sdk\Models\Components\CreateProductRequestConfiguration> $configurations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('configurations')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\CreateProductRequestConfiguration>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $configurations = null;

    /**
     *
     * @var ?string $impactToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('impact_token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $impactToken = null;

    /**
     * @param  string  $name
     * @param  string  $price
     * @param  ?\Factuarea\Sdk\Models\Components\CreateProductRequestItemKind  $itemKind
     * @param  ?\Factuarea\Sdk\Models\Components\CreateProductRequestBaseUnit  $baseUnit
     * @param  ?\Factuarea\Sdk\Models\Components\CreateProductRequestCatalogAvailabilityMode  $catalogAvailabilityMode
     * @param  ?string  $sku
     * @param  ?string  $description
     * @param  ?array<string>  $tags
     * @param  ?array<?string>  $specifications
     * @param  ?float  $stock
     * @param  ?float  $lowStockThreshold
     * @param  ?bool  $manageStock
     * @param  ?\Factuarea\Sdk\Models\Components\CreateProductRequestCurrency  $currency
     * @param  ?string  $taxRateId
     * @param  ?bool  $isActive
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $externalId
     * @param  ?array<\Factuarea\Sdk\Models\Components\CreateProductRequestOptionGroup>  $optionGroups
     * @param  ?array<\Factuarea\Sdk\Models\Components\CreateProductRequestConfiguration>  $configurations
     * @param  ?string  $impactToken
     * @phpstan-pure
     */
    public function __construct(string $name, string $price, ?CreateProductRequestItemKind $itemKind = null, ?CreateProductRequestBaseUnit $baseUnit = null, ?CreateProductRequestCatalogAvailabilityMode $catalogAvailabilityMode = null, ?string $sku = null, ?string $description = null, ?array $tags = null, ?array $specifications = null, ?float $stock = null, ?float $lowStockThreshold = null, ?bool $manageStock = null, ?CreateProductRequestCurrency $currency = null, ?string $taxRateId = null, ?bool $isActive = null, ?array $metadata = null, ?string $externalId = null, ?array $optionGroups = null, ?array $configurations = null, ?string $impactToken = null)
    {
        $this->name = $name;
        $this->price = $price;
        $this->itemKind = $itemKind;
        $this->baseUnit = $baseUnit;
        $this->catalogAvailabilityMode = $catalogAvailabilityMode;
        $this->sku = $sku;
        $this->description = $description;
        $this->tags = $tags;
        $this->specifications = $specifications;
        $this->stock = $stock;
        $this->lowStockThreshold = $lowStockThreshold;
        $this->manageStock = $manageStock;
        $this->currency = $currency;
        $this->taxRateId = $taxRateId;
        $this->isActive = $isActive;
        $this->metadata = $metadata;
        $this->externalId = $externalId;
        $this->optionGroups = $optionGroups;
        $this->configurations = $configurations;
        $this->impactToken = $impactToken;
    }
}