<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;

use Brick\DateTime\LocalDate;
/** CreateRecurringFromInvoiceRequest - Create a recurring invoice from an existing invoice, reusing its lines, client and series. The body supplies only the recurrence configuration: `frequency` and `start_on` are required; `end_on`, `name`, `description`, `notes`, `metadata`, `holiday_handling`, `days_before_due`, `max_occurrences` and an `auto_delivery` object are optional. */
class CreateRecurringFromInvoiceRequest
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Components\CreateRecurringFromInvoiceRequestFrequency $frequency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('frequency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateRecurringFromInvoiceRequestFrequency')]
    public CreateRecurringFromInvoiceRequestFrequency $frequency;

    /**
     *
     * @var LocalDate $startOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_on')]
    public LocalDate $startOn;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\CreateRecurringFromInvoiceRequestAutoDelivery $autoDelivery
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('auto_delivery')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\CreateRecurringFromInvoiceRequestAutoDelivery|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateRecurringFromInvoiceRequestAutoDelivery $autoDelivery = null;

    /**
     *
     * @var ?LocalDate $endOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_on')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $endOn = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?string $notes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('notes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $notes = null;

    /**
     * A free map of up to 50 key→value pairs for storing arbitrary structured data (values are strings up to 500 characters). Unlike `custom_fields` — an ordered list of typed `{field, value}` pairs with display semantics, present on the six document resources — `metadata` is an unordered map for opaque integration data; a document may carry both. The master resources (Client, Supplier) have no `custom_fields`, so their `metadata` doubles as the custom-fields store.
     *
     *
     * **Reserved keys (read-only).** When the system auto-issues an invoice from a payment correlation (Stripe/GoCardless/MONEI), it writes `stripe_subscription_id`, `stripe_invoice_id`, `billing_reason`, `period_start` and `period_end` into that invoice metadata automatically. Do not set or overwrite them by hand — the platform owns them and a manual value may be replaced when the correlation runs.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?string $holidayHandling
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('holiday_handling')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $holidayHandling = null;

    /**
     *
     * @var ?int $daysBeforeDue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('days_before_due')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $daysBeforeDue = null;

    /**
     *
     * @var ?int $maxOccurrences
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_occurrences')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxOccurrences = null;

    /**
     * @param  \Factuarea\Sdk\Models\Components\CreateRecurringFromInvoiceRequestFrequency  $frequency
     * @param  LocalDate  $startOn
     * @param  ?\Factuarea\Sdk\Models\Components\CreateRecurringFromInvoiceRequestAutoDelivery  $autoDelivery
     * @param  ?LocalDate  $endOn
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  ?string  $notes
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $holidayHandling
     * @param  ?int  $daysBeforeDue
     * @param  ?int  $maxOccurrences
     * @phpstan-pure
     */
    public function __construct(CreateRecurringFromInvoiceRequestFrequency $frequency, LocalDate $startOn, ?CreateRecurringFromInvoiceRequestAutoDelivery $autoDelivery = null, ?LocalDate $endOn = null, ?string $name = null, ?string $description = null, ?string $notes = null, ?array $metadata = null, ?string $holidayHandling = null, ?int $daysBeforeDue = null, ?int $maxOccurrences = null)
    {
        $this->frequency = $frequency;
        $this->startOn = $startOn;
        $this->autoDelivery = $autoDelivery;
        $this->endOn = $endOn;
        $this->name = $name;
        $this->description = $description;
        $this->notes = $notes;
        $this->metadata = $metadata;
        $this->holidayHandling = $holidayHandling;
        $this->daysBeforeDue = $daysBeforeDue;
        $this->maxOccurrences = $maxOccurrences;
    }
}