<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class CreateStockTransferRequestLine
{
    /**
     * Public ID of the article that travels, of the company in the path.
     *
     * @var string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    public string $productId;

    /**
     * Quantity to dispatch: greater than zero, with at most four decimals and up to 9999999999.9999. It is what LEAVES the origin; the received quantity is never sent and moves on its own when the transfer is received.
     *
     * @var float $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public float $quantity;

    /**
     * Public ID of the variant, when the line moves one specific variant of the article.
     *
     * @var ?string $productVariantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_variant_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productVariantId = null;

    /**
     * Public ID of the location inside the ORIGIN warehouse the goods leave from. Optional: this body checks it against your company, and that it also belongs to the origin warehouse of this transfer is checked by the transfer, which is what has both warehouses in front of it.
     *
     * @var ?string $originLocationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('origin_location_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $originLocationId = null;

    /**
     * Public ID of the location inside the DESTINATION warehouse the goods are placed at, with the same criterion.
     *
     * @var ?string $destinationLocationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_location_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationLocationId = null;

    /**
     * @param  string  $productId
     * @param  float  $quantity
     * @param  ?string  $productVariantId
     * @param  ?string  $originLocationId
     * @param  ?string  $destinationLocationId
     * @phpstan-pure
     */
    public function __construct(string $productId, float $quantity, ?string $productVariantId = null, ?string $originLocationId = null, ?string $destinationLocationId = null)
    {
        $this->productId = $productId;
        $this->quantity = $quantity;
        $this->productVariantId = $productVariantId;
        $this->originLocationId = $originLocationId;
        $this->destinationLocationId = $destinationLocationId;
    }
}