<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** DeclaracionResponsable - The producer-level VeriFactu Declaración Responsable (SIF compliance declaration issued by the system producer, Factuarea). Global per `version`, read-only — not per-company. */
class DeclaracionResponsable
{
    /**
     * UUID (v7) of the declaration.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\DeclaracionResponsableObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\DeclaracionResponsableObject')]
    public DeclaracionResponsableObject $object;

    /**
     * Version of the declaration (global key).
     *
     * @var string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    public string $version;

    /**
     * Identifier of the invoicing software system (SIF).
     *
     * @var string $systemId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('system_id')]
    public string $systemId;

    /**
     * Name of the invoicing software system (not its code: that is `system_id`).
     *
     * @var string $systemName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('system_name')]
    public string $systemName;

    /**
     * Components of the system (art. 15.d of Order HAC/1177/2024). An empty string in declarations that predate the full art. 15 content.
     *
     * @var string $components
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('components')]
    public string $components;

    /**
     * Tax ID (NIF) of the SIF producer.
     *
     * @var string $producerTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('producer_tax_id')]
    public string $producerTaxId;

    /**
     * Name of the SIF producer.
     *
     * @var string $producerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('producer_name')]
    public string $producerName;

    /**
     * Postal address of the SIF producer (art. 15.j). An empty string in declarations that predate the full art. 15 content.
     *
     * @var string $producerAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('producer_address')]
    public string $producerAddress;

    /**
     * Whether the system can ONLY operate as VERI*FACTU (art. 15.e, `TipoUsoPosibleSoloVerifactu`). It declares a possibility of the system, not the mode of a company.
     *
     * @var bool $verifactuOnly
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verifactu_only')]
    public bool $verifactuOnly;

    /**
     * Whether the system can serve several obliged taxpayers (art. 15.f, `TipoUsoPosibleMultiOT`). It declares a possibility of the system; the per-customer `IndicadorMultiplesOT` reported on each record is computed separately and is not part of art. 15.
     *
     * @var bool $multiOt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('multi_ot')]
    public bool $multiOt;

    /**
     * Date of the declaration.
     *
     * @var \DateTime $declaredAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('declared_at')]
    public \DateTime $declaredAt;

    /**
     * Place where the declaration is signed.
     *
     * @var string $signingPlace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signing_place')]
    public string $signingPlace;

    /**
     * SHA-256 hash of the declaration content for integrity verification (the full content is not exposed).
     *
     * @var string $contentHash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content_hash')]
    public string $contentHash;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * Signature types the system uses when it also works outside VERI*FACTU (art. 15.g). `null` when the system only works as VERI*FACTU and in declarations that predate the full art. 15 content.
     *
     * @var ?string $signatureTypes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signature_types')]
    public ?string $signatureTypes;

    /**
     * @param  string  $id
     * @param  \Factuarea\Sdk\Models\Components\DeclaracionResponsableObject  $object
     * @param  string  $version
     * @param  string  $systemId
     * @param  string  $systemName
     * @param  string  $components
     * @param  string  $producerTaxId
     * @param  string  $producerName
     * @param  string  $producerAddress
     * @param  bool  $verifactuOnly
     * @param  bool  $multiOt
     * @param  \DateTime  $declaredAt
     * @param  string  $signingPlace
     * @param  string  $contentHash
     * @param  \DateTime  $createdAt
     * @param  ?string  $signatureTypes
     * @phpstan-pure
     */
    public function __construct(string $id, DeclaracionResponsableObject $object, string $version, string $systemId, string $systemName, string $components, string $producerTaxId, string $producerName, string $producerAddress, bool $verifactuOnly, bool $multiOt, \DateTime $declaredAt, string $signingPlace, string $contentHash, \DateTime $createdAt, ?string $signatureTypes = null)
    {
        $this->id = $id;
        $this->object = $object;
        $this->version = $version;
        $this->systemId = $systemId;
        $this->systemName = $systemName;
        $this->components = $components;
        $this->producerTaxId = $producerTaxId;
        $this->producerName = $producerName;
        $this->producerAddress = $producerAddress;
        $this->verifactuOnly = $verifactuOnly;
        $this->multiOt = $multiOt;
        $this->declaredAt = $declaredAt;
        $this->signingPlace = $signingPlace;
        $this->contentHash = $contentHash;
        $this->createdAt = $createdAt;
        $this->signatureTypes = $signatureTypes;
    }
}