<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Status of the PHYSICAL axis of the delivery note — where the goods are — which is ORTHOGONAL to the `status` above: no transition of this axis changes the commercial status and no commercial transition changes this one. It is NEVER `null`: its column is `NOT NULL DEFAULT pending`, so a note that never entered picking publishes the initial status of the catalog. Its closed catalog is published by its own operation (`GET .../delivery-notes/fulfilment-statuses`) and shares no value with the catalog of delivery note statuses. */
enum DeliveryNoteFulfilmentStatus: string
{
    case Pending = 'pending';
    case Picking = 'picking';
    case Prepared = 'prepared';
    case HandedOver = 'handed_over';
    case InTransit = 'in_transit';
    case Delivered = 'delivered';
    case Failed = 'failed';
}
