<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class DuplicateTaskV1Request
{
    /**
     * Title of the copy (1 to 500 characters). When omitted, it keeps the title of the original.
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * @param  ?string  $title
     * @phpstan-pure
     */
    public function __construct(?string $title = null)
    {
        $this->title = $title;
    }
}