<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** EventCatalogEntry - A single event type available for webhook subscriptions. The full catalog is returned by `GET /v1/event-catalog`. */
class EventCatalogEntry
{
    /**
     * Event identifier (e.g. `invoice.created`, `quote.approved`).
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * High-level group derived from the prefix (`invoice`, `quote`, `client`, …).
     *
     * @var string $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    public string $category;

    /**
     * Human-readable description in Spanish.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * `available` if the event is emitted today; `coming_soon` if reserved for a future release.
     *
     * @var \Factuarea\Sdk\Models\Components\EventCatalogEntryStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\EventCatalogEntryStatus')]
    public EventCatalogEntryStatus $status;

    /**
     * @param  string  $name
     * @param  string  $category
     * @param  string  $description
     * @param  \Factuarea\Sdk\Models\Components\EventCatalogEntryStatus  $status
     * @phpstan-pure
     */
    public function __construct(string $name, string $category, string $description, EventCatalogEntryStatus $status)
    {
        $this->name = $name;
        $this->category = $category;
        $this->description = $description;
        $this->status = $status;
    }
}