<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


enum FindTaxReportByPeriodV1RequestType: string
{
    case Modelo303 = 'modelo_303';
    case Modelo347 = 'modelo_347';
}
