<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class LinkTaskToEntityV1Request
{
    /**
     * Entity type: `invoice`, `quote`, `proforma`, `delivery_note`, `purchase_invoice`, `recurring_invoice`, `contact`, `product` or `employee`.
     *
     * @var \Factuarea\Sdk\Models\Components\LinkTaskToEntityV1RequestEntityType $entityType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entity_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\LinkTaskToEntityV1RequestEntityType')]
    public LinkTaskToEntityV1RequestEntityType $entityType;

    /**
     * Public `id` (UUID) of the company entity.
     *
     * @var string $entityId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entity_id')]
    public string $entityId;

    /**
     * @param  \Factuarea\Sdk\Models\Components\LinkTaskToEntityV1RequestEntityType  $entityType
     * @param  string  $entityId
     * @phpstan-pure
     */
    public function __construct(LinkTaskToEntityV1RequestEntityType $entityType, string $entityId)
    {
        $this->entityType = $entityType;
        $this->entityId = $entityId;
    }
}