<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Always `monthly_register_signature`. */
enum MonthlyRegisterSignatureObject: string
{
    case MonthlyRegisterSignature = 'monthly_register_signature';
}
