<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class Pause
{
    /**
     * Start of a break in ISO 8601.
     *
     * @var \DateTime $start
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start')]
    public \DateTime $start;

    /**
     * End of a break in ISO 8601 (after its start).
     *
     * @var \DateTime $end
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end')]
    public \DateTime $end;

    /**
     * @param  \DateTime  $start
     * @param  \DateTime  $end
     * @phpstan-pure
     */
    public function __construct(\DateTime $start, \DateTime $end)
    {
        $this->start = $start;
        $this->end = $end;
    }
}