<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Preferred payment method. If `direct_debit` or `sepa_direct_debit`, the client must have at least one bank account marked as default. */
enum PaymentPreferencesMethod: string
{
    case BankTransfer = 'bank_transfer';
    case DirectDebit = 'direct_debit';
    case SepaDirectDebit = 'sepa_direct_debit';
    case Cash = 'cash';
    case CreditCard = 'credit_card';
    case Check = 'check';
    case Paypal = 'paypal';
    case Bizum = 'bizum';
    case Other = 'other';
}
