<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class PurchaseScanTotals
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField $subtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\PurchaseScanExtractedField')]
    public PurchaseScanExtractedField $subtotal;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField $tax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\PurchaseScanExtractedField')]
    public PurchaseScanExtractedField $tax;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField $retention
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('retention')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\PurchaseScanExtractedField')]
    public PurchaseScanExtractedField $retention;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField $surcharge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('surcharge')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\PurchaseScanExtractedField')]
    public PurchaseScanExtractedField $surcharge;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\PurchaseScanExtractedField')]
    public PurchaseScanExtractedField $total;

    /**
     * @param  \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField  $subtotal
     * @param  \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField  $tax
     * @param  \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField  $retention
     * @param  \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField  $surcharge
     * @param  \Factuarea\Sdk\Models\Components\PurchaseScanExtractedField  $total
     * @phpstan-pure
     */
    public function __construct(PurchaseScanExtractedField $subtotal, PurchaseScanExtractedField $tax, PurchaseScanExtractedField $retention, PurchaseScanExtractedField $surcharge, PurchaseScanExtractedField $total)
    {
        $this->subtotal = $subtotal;
        $this->tax = $tax;
        $this->retention = $retention;
        $this->surcharge = $surcharge;
        $this->total = $total;
    }
}