<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


enum PurchaseScanCode: string
{
    case OcrTemporarilyUnavailable = 'ocr_temporarily_unavailable';
    case ScanStorageUnavailable = 'scan_storage_unavailable';
    case FileSafetyUnavailable = 'file_safety_unavailable';
    case InboundProviderUnavailable = 'inbound_provider_unavailable';
    case ResourceLocked = 'resource_locked';
    case QueueDeliveryFailed = 'queue_delivery_failed';
    case PurchaseScannerDisabled = 'purchase_scanner_disabled';
    case OcrCompanyQuotaExceeded = 'ocr_company_quota_exceeded';
    case ModuleUpgradeRequired = 'module_upgrade_required';
    case UnsupportedScanFormat = 'unsupported_scan_format';
    case UnsupportedPurchaseDocumentType = 'unsupported_purchase_document_type';
    case UnsafeScanFile = 'unsafe_scan_file';
    case ScanPageLimitExceeded = 'scan_page_limit_exceeded';
    case PurchaseScannerInternalError = 'purchase_scanner_internal_error';
}
