<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class PurchaseScanListItemLastError
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Components\PurchaseScanListItemCode $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\PurchaseScanListItemCode')]
    public PurchaseScanListItemCode $code;

    /**
     *
     * @var bool $recoverable
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recoverable')]
    public bool $recoverable;

    /**
     * @param  \Factuarea\Sdk\Models\Components\PurchaseScanListItemCode  $code
     * @param  bool  $recoverable
     * @phpstan-pure
     */
    public function __construct(PurchaseScanListItemCode $code, bool $recoverable)
    {
        $this->code = $code;
        $this->recoverable = $recoverable;
    }
}