<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;

use Brick\DateTime\LocalDate;
/** Quote - A sales quote that can be converted to an invoice. */
class Quote
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\QuoteObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\QuoteObject')]
    public QuoteObject $object;

    /**
     *
     * @var string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    public string $number;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\SeriesRef $series
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('series')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\SeriesRef')]
    public SeriesRef $series;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\ClientRef $client
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\ClientRef')]
    public ClientRef $client;

    /**
     * Quote lifecycle status (draft, sent, accepted, rejected, expired, converted, cancelled).
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     *
     * @var LocalDate $issuedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issued_on')]
    public LocalDate $issuedOn;

    /**
     *
     * @var float $subtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal')]
    public float $subtotal;

    /**
     * Aggregated tax amount. Use total_vat/total_retention/total_surcharge for breakdown.
     *
     * @var float $taxesTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxes_total')]
    public float $taxesTotal;

    /**
     * Sum of VAT (IVA) across all lines.
     *
     * @var float $totalVat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_vat')]
    public float $totalVat;

    /**
     * Sum of withholding (IRPF/retention) across all lines.
     *
     * @var float $totalRetention
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_retention')]
    public float $totalRetention;

    /**
     * Sum of equivalence surcharge (recargo de equivalencia) across all lines.
     *
     * @var float $totalSurcharge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_surcharge')]
    public float $totalSurcharge;

    /**
     *
     * @var float $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public float $total;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * $lines
     *
     * @var array<\Factuarea\Sdk\Models\Components\QuoteLine> $lines
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lines')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\QuoteLine>')]
    public array $lines;

    /**
     * Whether the public share link is currently active.
     *
     * @var bool $linkIsActive
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link_is_active')]
    public bool $linkIsActive;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public \DateTime $updatedAt;

    /**
     *
     * @var ?LocalDate $validUntil
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('valid_until')]
    public ?LocalDate $validUntil;

    /**
     *
     * @var ?\DateTime $acceptedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accepted_at')]
    public ?\DateTime $acceptedAt;

    /**
     *
     * @var ?\DateTime $rejectedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rejected_at')]
    public ?\DateTime $rejectedAt;

    /**
     * UUID (v7) of the invoice this quote was converted into, if any.
     *
     * @var ?string $convertedToId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_to_id')]
    public ?string $convertedToId;

    /**
     * Human-readable number of the invoice this quote was converted into (e.g. "F-2026-00042"). null if not converted.
     *
     * @var ?string $convertedInvoiceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_invoice_number')]
    public ?string $convertedInvoiceNumber;

    /**
     *
     * @var ?string $notes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('notes')]
    public ?string $notes;

    /**
     * Free-text terms and conditions rendered on the quote PDF.
     *
     * @var ?string $terms
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('terms')]
    public ?string $terms;

    /**
     * Up to 50 key-value pairs for storing additional structured data. Values must be strings up to 500 characters.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    public ?array $metadata;

    /**
     * Expiry date of the public share link, or null if unlimited.
     *
     * @var ?\DateTime $linkExpiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link_expires_at')]
    public ?\DateTime $linkExpiresAt;

    /**
     * @param  string  $id
     * @param  \Factuarea\Sdk\Models\Components\QuoteObject  $object
     * @param  string  $number
     * @param  \Factuarea\Sdk\Models\Components\SeriesRef  $series
     * @param  \Factuarea\Sdk\Models\Components\ClientRef  $client
     * @param  string  $status
     * @param  LocalDate  $issuedOn
     * @param  float  $subtotal
     * @param  float  $taxesTotal
     * @param  float  $totalVat
     * @param  float  $totalRetention
     * @param  float  $totalSurcharge
     * @param  float  $total
     * @param  string  $currency
     * @param  array<\Factuarea\Sdk\Models\Components\QuoteLine>  $lines
     * @param  bool  $linkIsActive
     * @param  \DateTime  $createdAt
     * @param  \DateTime  $updatedAt
     * @param  ?LocalDate  $validUntil
     * @param  ?\DateTime  $acceptedAt
     * @param  ?\DateTime  $rejectedAt
     * @param  ?string  $convertedToId
     * @param  ?string  $convertedInvoiceNumber
     * @param  ?string  $notes
     * @param  ?string  $terms
     * @param  ?array<string, string>  $metadata
     * @param  ?\DateTime  $linkExpiresAt
     * @phpstan-pure
     */
    public function __construct(string $id, QuoteObject $object, string $number, SeriesRef $series, ClientRef $client, string $status, LocalDate $issuedOn, float $subtotal, float $taxesTotal, float $totalVat, float $totalRetention, float $totalSurcharge, float $total, string $currency, array $lines, bool $linkIsActive, \DateTime $createdAt, \DateTime $updatedAt, ?LocalDate $validUntil = null, ?\DateTime $acceptedAt = null, ?\DateTime $rejectedAt = null, ?string $convertedToId = null, ?string $convertedInvoiceNumber = null, ?string $notes = null, ?string $terms = null, ?array $metadata = null, ?\DateTime $linkExpiresAt = null)
    {
        $this->id = $id;
        $this->object = $object;
        $this->number = $number;
        $this->series = $series;
        $this->client = $client;
        $this->status = $status;
        $this->issuedOn = $issuedOn;
        $this->subtotal = $subtotal;
        $this->taxesTotal = $taxesTotal;
        $this->totalVat = $totalVat;
        $this->totalRetention = $totalRetention;
        $this->totalSurcharge = $totalSurcharge;
        $this->total = $total;
        $this->currency = $currency;
        $this->lines = $lines;
        $this->linkIsActive = $linkIsActive;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->validUntil = $validUntil;
        $this->acceptedAt = $acceptedAt;
        $this->rejectedAt = $rejectedAt;
        $this->convertedToId = $convertedToId;
        $this->convertedInvoiceNumber = $convertedInvoiceNumber;
        $this->notes = $notes;
        $this->terms = $terms;
        $this->metadata = $metadata;
        $this->linkExpiresAt = $linkExpiresAt;
    }
}