<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class RecurringInvoiceActivityPerformedBy
{
    /**
     * Type of actor that originated the event.
     *
     * @var \Factuarea\Sdk\Models\Components\RecurringInvoiceActivityType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\RecurringInvoiceActivityType')]
    public RecurringInvoiceActivityType $type;

    /**
     * UUID (v7) of the user who performed the action.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Nombre del usuario en el momento del evento.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public ?string $name;

    /**
     * @param  \Factuarea\Sdk\Models\Components\RecurringInvoiceActivityType  $type
     * @param  string  $id
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(RecurringInvoiceActivityType $type, string $id, ?string $name = null)
    {
        $this->type = $type;
        $this->id = $id;
        $this->name = $name;
    }
}