<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class ReorderProjectColumnsV1Request
{
    /**
     * `id` of ALL the columns of the project, in the desired order.
     *
     * @var array<string> $columnIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('column_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $columnIds;

    /**
     * @param  array<string>  $columnIds
     * @phpstan-pure
     */
    public function __construct(array $columnIds)
    {
        $this->columnIds = $columnIds;
    }
}