<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class RetiredPriceListTargetOption
{
    /**
     *
     * @var string $valueId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value_id')]
    public string $valueId;

    /**
     *
     * @var string $valueName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value_name')]
    public string $valueName;

    /**
     *
     * @var ?string $groupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('group_id')]
    public ?string $groupId;

    /**
     *
     * @var ?string $groupName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('group_name')]
    public ?string $groupName;

    /**
     * @param  string  $valueId
     * @param  string  $valueName
     * @param  ?string  $groupId
     * @param  ?string  $groupName
     * @phpstan-pure
     */
    public function __construct(string $valueId, string $valueName, ?string $groupId = null, ?string $groupName = null)
    {
        $this->valueId = $valueId;
        $this->valueName = $valueName;
        $this->groupId = $groupId;
        $this->groupName = $groupName;
    }
}