<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Reason the payment was reverted, from the closed catalog. `null` while the payment is in force. */
enum ReversalReason: string
{
    case DirectDebitReturn = 'direct_debit_return';
    case CardDispute = 'card_dispute';
    case MisappliedPayment = 'misapplied_payment';
    case BouncedEffect = 'bounced_effect';
    case RecordingError = 'recording_error';
}
