<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class SendEmployeeInvitationRequest
{
    /**
     * Email of the employee to invite (the `employee` role is set by the server).
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     * @param  string  $email
     * @phpstan-pure
     */
    public function __construct(string $email)
    {
        $this->email = $email;
    }
}