<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** StockReservationBatchResult - The acknowledgement of an operation that touches SEVERAL reservations at once: the creation, which holds one line after another, and the release BY HOLDER, which sweeps everything a holder was keeping. One single shape answers both, so an integration models one type and not two. */
class StockReservationBatchResult
{
    /**
     * Always `stock_reservation_batch_result`.
     *
     * @var \Factuarea\Sdk\Models\Components\StockReservationBatchResultObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\StockReservationBatchResultObject')]
    public StockReservationBatchResultObject $object;

    /**
     * Number of reservations the acknowledgement covers: created by the creation, effectively released by the release by holder. Releasing a holder that was keeping nothing answers in the green with zero, which is what makes that operation safe to repeat.
     *
     * @var int $count
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('count')]
    public int $count;

    /**
     * Body of each reservation CREATED. The creation fills it —and it may be shorter than the lines that were sent, because holds for the same destination are grouped—; the release by holder always returns it EMPTY, because its contract is the count and not the bodies.
     *
     * @var array<\Factuarea\Sdk\Models\Components\StockReservation> $reservations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reservations')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\StockReservation>')]
    public array $reservations;

    /**
     * @param  \Factuarea\Sdk\Models\Components\StockReservationBatchResultObject  $object
     * @param  int  $count
     * @param  array<\Factuarea\Sdk\Models\Components\StockReservation>  $reservations
     * @phpstan-pure
     */
    public function __construct(StockReservationBatchResultObject $object, int $count, array $reservations)
    {
        $this->object = $object;
        $this->count = $count;
        $this->reservations = $reservations;
    }
}