<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class SupplierProductOffer
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Factuarea\Sdk\Models\Components\SupplierProductOfferObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\SupplierProductOfferObject')]
    public SupplierProductOfferObject $object;

    /**
     *
     * @var string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    public string $productId;

    /**
     *
     * @var string $supplierId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('supplier_id')]
    public string $supplierId;

    /**
     *
     * @var string $purchaseUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('purchase_unit')]
    public string $purchaseUnit;

    /**
     *
     * @var string $conversionFactor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conversion_factor')]
    public string $conversionFactor;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var string $availability
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('availability')]
    public string $availability;

    /**
     *
     * @var bool $preferred
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('preferred')]
    public bool $preferred;

    /**
     *
     * @var bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    public bool $active;

    /**
     *
     * @var ?string $variantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variant_id')]
    public ?string $variantId;

    /**
     *
     * @var ?string $supplierSku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('supplier_sku')]
    public ?string $supplierSku;

    /**
     *
     * @var ?float $unitCost
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit_cost')]
    public ?float $unitCost;

    /**
     *
     * @var ?string $minimumQuantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('minimum_quantity')]
    public ?string $minimumQuantity;

    /**
     *
     * @var ?int $leadTimeDays
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lead_time_days')]
    public ?int $leadTimeDays;

    /**
     * @param  string  $id
     * @param  \Factuarea\Sdk\Models\Components\SupplierProductOfferObject  $object
     * @param  string  $productId
     * @param  string  $supplierId
     * @param  string  $purchaseUnit
     * @param  string  $conversionFactor
     * @param  string  $currency
     * @param  string  $availability
     * @param  bool  $preferred
     * @param  bool  $active
     * @param  ?string  $variantId
     * @param  ?string  $supplierSku
     * @param  ?float  $unitCost
     * @param  ?string  $minimumQuantity
     * @param  ?int  $leadTimeDays
     * @phpstan-pure
     */
    public function __construct(string $id, SupplierProductOfferObject $object, string $productId, string $supplierId, string $purchaseUnit, string $conversionFactor, string $currency, string $availability, bool $preferred, bool $active, ?string $variantId = null, ?string $supplierSku = null, ?float $unitCost = null, ?string $minimumQuantity = null, ?int $leadTimeDays = null)
    {
        $this->id = $id;
        $this->object = $object;
        $this->productId = $productId;
        $this->supplierId = $supplierId;
        $this->purchaseUnit = $purchaseUnit;
        $this->conversionFactor = $conversionFactor;
        $this->currency = $currency;
        $this->availability = $availability;
        $this->preferred = $preferred;
        $this->active = $active;
        $this->variantId = $variantId;
        $this->supplierSku = $supplierSku;
        $this->unitCost = $unitCost;
        $this->minimumQuantity = $minimumQuantity;
        $this->leadTimeDays = $leadTimeDays;
    }
}