<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** TaxReportPreview - Preview (dry-run computation, without persisting any file) of a Modelo 303/347 for a period. Lets the integrator validate the amounts before generating the final report. Amounts are expressed in euro cents (integers). */
class TaxReportPreview
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Components\TaxReportPreviewObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\TaxReportPreviewObject')]
    public TaxReportPreviewObject $object;

    /**
     * Type of previewed report.
     *
     * @var \Factuarea\Sdk\Models\Components\TaxReportPreviewType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\TaxReportPreviewType')]
    public TaxReportPreviewType $type;

    /**
     * Previewed fiscal period.
     *
     * @var \Factuarea\Sdk\Models\Components\TaxReportPreviewPeriod $period
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('period')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\TaxReportPreviewPeriod')]
    public TaxReportPreviewPeriod $period;

    /**
     * Breakdown by VAT rate (Modelo 303 only). Map indexed by tax rate → `{base, cuota}` in cents. Empty for Modelo 347.
     *
     * @var array<string, \Factuarea\Sdk\Models\Components\Breakdown303> $breakdown303
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('breakdown_303')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Factuarea\Sdk\Models\Components\Breakdown303>')]
    public array $breakdown303;

    /**
     * Aggregated totals of the declaration (amounts in cents).
     *
     * @var array<string, int> $totals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totals')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, int>')]
    public array $totals;

    /**
     * Operations with clients that exceed the Modelo 347 threshold (Modelo 347 only). Empty for Modelo 303.
     *
     * @var array<\Factuarea\Sdk\Models\Components\Clients347> $clients347
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clients_347')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\Clients347>')]
    public array $clients347;

    /**
     * Operations with suppliers that exceed the Modelo 347 threshold (Modelo 347 only). Empty for Modelo 303.
     *
     * @var array<\Factuarea\Sdk\Models\Components\Suppliers347> $suppliers347
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('suppliers_347')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\Suppliers347>')]
    public array $suppliers347;

    /**
     * Number of issued invoices considered in the period.
     *
     * @var int $invoiceCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoice_count')]
    public int $invoiceCount;

    /**
     * Number of purchase invoices considered in the period.
     *
     * @var int $purchaseInvoiceCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('purchase_invoice_count')]
    public int $purchaseInvoiceCount;

    /**
     * Non-blocking warnings detected during the computation (e.g. invoices with incomplete data).
     *
     * @var array<string> $warnings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('warnings')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $warnings;

    /**
     * @param  \Factuarea\Sdk\Models\Components\TaxReportPreviewObject  $object
     * @param  \Factuarea\Sdk\Models\Components\TaxReportPreviewType  $type
     * @param  \Factuarea\Sdk\Models\Components\TaxReportPreviewPeriod  $period
     * @param  array<string, \Factuarea\Sdk\Models\Components\Breakdown303>  $breakdown303
     * @param  array<string, int>  $totals
     * @param  array<\Factuarea\Sdk\Models\Components\Clients347>  $clients347
     * @param  array<\Factuarea\Sdk\Models\Components\Suppliers347>  $suppliers347
     * @param  int  $invoiceCount
     * @param  int  $purchaseInvoiceCount
     * @param  array<string>  $warnings
     * @phpstan-pure
     */
    public function __construct(TaxReportPreviewObject $object, TaxReportPreviewType $type, TaxReportPreviewPeriod $period, array $breakdown303, array $totals, array $clients347, array $suppliers347, int $invoiceCount, int $purchaseInvoiceCount, array $warnings)
    {
        $this->object = $object;
        $this->type = $type;
        $this->period = $period;
        $this->breakdown303 = $breakdown303;
        $this->totals = $totals;
        $this->clients347 = $clients347;
        $this->suppliers347 = $suppliers347;
        $this->invoiceCount = $invoiceCount;
        $this->purchaseInvoiceCount = $purchaseInvoiceCount;
        $this->warnings = $warnings;
    }
}