<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class UpdateInvoiceRequestLine
{
    /**
     *
     * @var ?float $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $quantity = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?float $unitPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit_price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $unitPrice = null;

    /**
     *
     * @var ?string $taxRateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxRateId = null;

    /**
     *
     * @var ?float $taxRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxRate = null;

    /**
     *
     * @var ?float $retentionRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('retention_rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $retentionRate = null;

    /**
     *
     * @var ?float $surchargeRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('surcharge_rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $surchargeRate = null;

    /**
     *
     * @var ?string $retentionRateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('retention_rate_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $retentionRateId = null;

    /**
     *
     * @var ?string $surchargeRateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('surcharge_rate_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $surchargeRateId = null;

    /**
     *
     * @var ?string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productId = null;

    /**
     *
     * @var ?string $variantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variant_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $variantId = null;

    /**
     *
     * @var ?string $presentationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('presentation_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $presentationId = null;

    /**
     *
     * @var ?float $confirmedBaseQuantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('confirmed_base_quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $confirmedBaseQuantity = null;

    /**
     *
     * @var ?float $discountPercent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_percent')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $discountPercent = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestRegimeKey $regimeKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('regime_key')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestRegimeKey|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceRequestRegimeKey $regimeKey = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestExemptionReason $exemptionReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemption_reason')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestExemptionReason|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceRequestExemptionReason $exemptionReason = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestIndirectTaxRegime $indirectTaxRegime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('indirect_tax_regime')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestIndirectTaxRegime|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceRequestIndirectTaxRegime $indirectTaxRegime = null;

    /**
     * Kind of line: `NORMAL` (default) for an ordinary line of your own operation, or `SUPLIDO` for a DISBURSEMENT — an amount you paid in the name and on behalf of the client and now re-invoice at cost, which stays out of the taxable base (art. 78.Tres.3 LIVA). Replacing the lines of a draft re-applies the same rules, so keep the field when you resend a line you read from the invoice: sending it as `NORMAL` (or omitting it) turns the disbursement into an ordinary taxable line and changes the invoice amount.
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestLineType $lineType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestLineType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceRequestLineType $lineType = null;

    /**
     * Reference of the supporting document that originated the disbursement — the receipt or fee number issued by the public body (up to 100 characters). REQUIRED when `line_type` is `SUPLIDO`; leave it out on a normal line.
     *
     * @var ?string $sourceInvoiceReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_invoice_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceInvoiceReference = null;

    /**
     * Optional traceability of a disbursement: list of IDs (UUID v7) of your own purchase invoices that back it. A purchase invoice of another company is rejected with 422.
     *
     * @var ?array<string> $sourceInvoiceIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_invoice_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $sourceInvoiceIds = null;

    /**
     * Unit of measure printed next to the quantity on the document (`hours`, `kg`, `units`, …), up to 20 characters. Presentation only: free text, no closed catalog and no fiscal effect.
     *
     * @var ?string $unit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $unit = null;

    /**
     * Free-text wording of the exemption provision of this line (up to 255 characters), printed under the line description to satisfy the mention required by art. 6.1.j of Royal Decree 1619/2012 when the catalogued cause does not cover it.
     *
     * @var ?string $exemptionReasonText
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemption_reason_text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $exemptionReasonText = null;

    /**
     * Optional CHECKSUM of the line total. When sent, it is compared against the total this API computes and the request is rejected with 422 (`line_total_checksum_mismatch`, with the expected and received values in `error.details`) when they differ by more than one cent. Never stored and never returned.
     *
     * @var ?float $lineTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $lineTotal = null;

    /**
     *
     * @var ?string $configurationUuid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('configuration_uuid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $configurationUuid = null;

    /**
     * $options
     *
     * @var ?array<\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestOption> $options
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('options')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestOption>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $options = null;

    /**
     *
     * @var ?string $configurationSignature
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('configuration_signature')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $configurationSignature = null;

    /**
     *
     * @var ?string $configurationName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('configuration_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $configurationName = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestPriceSource $priceSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestPriceSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceRequestPriceSource $priceSource = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestPriceSemantics $priceSemantics
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_semantics')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestPriceSemantics|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceRequestPriceSemantics $priceSemantics = null;

    /**
     *
     * @var ?float $priceAdjustmentTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_adjustment_total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $priceAdjustmentTotal = null;

    /**
     *
     * @var ?bool $optionAdjustmentsAbsorbed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('option_adjustments_absorbed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $optionAdjustmentsAbsorbed = null;

    /**
     * @param  ?float  $quantity
     * @param  ?string  $description
     * @param  ?float  $unitPrice
     * @param  ?string  $taxRateId
     * @param  ?float  $taxRate
     * @param  ?float  $retentionRate
     * @param  ?float  $surchargeRate
     * @param  ?string  $retentionRateId
     * @param  ?string  $surchargeRateId
     * @param  ?string  $productId
     * @param  ?string  $variantId
     * @param  ?string  $presentationId
     * @param  ?float  $confirmedBaseQuantity
     * @param  ?float  $discountPercent
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestRegimeKey  $regimeKey
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestExemptionReason  $exemptionReason
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestIndirectTaxRegime  $indirectTaxRegime
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestLineType  $lineType
     * @param  ?string  $sourceInvoiceReference
     * @param  ?array<string>  $sourceInvoiceIds
     * @param  ?string  $unit
     * @param  ?string  $exemptionReasonText
     * @param  ?float  $lineTotal
     * @param  ?string  $configurationUuid
     * @param  ?array<\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestOption>  $options
     * @param  ?string  $configurationSignature
     * @param  ?string  $configurationName
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestPriceSource  $priceSource
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateInvoiceRequestPriceSemantics  $priceSemantics
     * @param  ?float  $priceAdjustmentTotal
     * @param  ?bool  $optionAdjustmentsAbsorbed
     * @phpstan-pure
     */
    public function __construct(?float $quantity = null, ?string $description = null, ?float $unitPrice = null, ?string $taxRateId = null, ?float $taxRate = null, ?float $retentionRate = null, ?float $surchargeRate = null, ?string $retentionRateId = null, ?string $surchargeRateId = null, ?string $productId = null, ?string $variantId = null, ?string $presentationId = null, ?float $confirmedBaseQuantity = null, ?float $discountPercent = null, ?UpdateInvoiceRequestRegimeKey $regimeKey = null, ?UpdateInvoiceRequestExemptionReason $exemptionReason = null, ?UpdateInvoiceRequestIndirectTaxRegime $indirectTaxRegime = null, ?UpdateInvoiceRequestLineType $lineType = null, ?string $sourceInvoiceReference = null, ?array $sourceInvoiceIds = null, ?string $unit = null, ?string $exemptionReasonText = null, ?float $lineTotal = null, ?string $configurationUuid = null, ?array $options = null, ?string $configurationSignature = null, ?string $configurationName = null, ?UpdateInvoiceRequestPriceSource $priceSource = null, ?UpdateInvoiceRequestPriceSemantics $priceSemantics = null, ?float $priceAdjustmentTotal = null, ?bool $optionAdjustmentsAbsorbed = null)
    {
        $this->quantity = $quantity;
        $this->description = $description;
        $this->unitPrice = $unitPrice;
        $this->taxRateId = $taxRateId;
        $this->taxRate = $taxRate;
        $this->retentionRate = $retentionRate;
        $this->surchargeRate = $surchargeRate;
        $this->retentionRateId = $retentionRateId;
        $this->surchargeRateId = $surchargeRateId;
        $this->productId = $productId;
        $this->variantId = $variantId;
        $this->presentationId = $presentationId;
        $this->confirmedBaseQuantity = $confirmedBaseQuantity;
        $this->discountPercent = $discountPercent;
        $this->regimeKey = $regimeKey;
        $this->exemptionReason = $exemptionReason;
        $this->indirectTaxRegime = $indirectTaxRegime;
        $this->lineType = $lineType;
        $this->sourceInvoiceReference = $sourceInvoiceReference;
        $this->sourceInvoiceIds = $sourceInvoiceIds;
        $this->unit = $unit;
        $this->exemptionReasonText = $exemptionReasonText;
        $this->lineTotal = $lineTotal;
        $this->configurationUuid = $configurationUuid;
        $this->options = $options;
        $this->configurationSignature = $configurationSignature;
        $this->configurationName = $configurationName;
        $this->priceSource = $priceSource;
        $this->priceSemantics = $priceSemantics;
        $this->priceAdjustmentTotal = $priceAdjustmentTotal;
        $this->optionAdjustmentsAbsorbed = $optionAdjustmentsAbsorbed;
    }
}