<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


enum UpdateWebhookEndpointRequestEnabledEvent: string
{
    case InvoiceCreated = 'invoice.created';
    case InvoiceUpdated = 'invoice.updated';
    case InvoiceSent = 'invoice.sent';
    case InvoicePaid = 'invoice.paid';
    case InvoiceCancelled = 'invoice.cancelled';
    case InvoiceAnnulled = 'invoice.annulled';
    case InvoiceOverdue = 'invoice.overdue';
    case InvoiceDeleted = 'invoice.deleted';
    case InvoiceNumberAssigned = 'invoice.number_assigned';
    case InvoiceRectified = 'invoice.rectified';
    case InvoiceEmailSent = 'invoice.email_sent';
    case InvoiceEmailFailed = 'invoice.email_failed';
    case InvoicePaymentReminderSent = 'invoice.payment_reminder_sent';
    case InvoiceSimplifiedCreated = 'invoice.simplified_created';
    case InvoiceSimplifiedSubstituted = 'invoice.simplified_substituted';
    case InvoiceSubstitutedByComplete = 'invoice.substituted_by_complete';
    case InvoiceVerifactuSubmitted = 'invoice.verifactu_submitted';
    case InvoiceVerifactuFailed = 'invoice.verifactu_failed';
    case InvoiceMetadataChanged = 'invoice.metadata_changed';
    case QuoteCreated = 'quote.created';
    case QuoteUpdated = 'quote.updated';
    case QuoteDeleted = 'quote.deleted';
    case QuoteApproved = 'quote.approved';
    case QuoteRejected = 'quote.rejected';
    case QuoteConverted = 'quote.converted';
    case QuoteExpired = 'quote.expired';
    case QuoteMarkedAsPending = 'quote.marked_as_pending';
    case QuoteCancelled = 'quote.cancelled';
    case QuoteNumberAssigned = 'quote.number_assigned';
    case QuoteMetadataChanged = 'quote.metadata_changed';
    case ProformaCreated = 'proforma.created';
    case ProformaUpdated = 'proforma.updated';
    case ProformaDeleted = 'proforma.deleted';
    case ProformaAccepted = 'proforma.accepted';
    case ProformaRejected = 'proforma.rejected';
    case ProformaCancelled = 'proforma.cancelled';
    case ProformaExpired = 'proforma.expired';
    case ProformaConvertedToInvoice = 'proforma.converted_to_invoice';
    case ProformaNumberAssigned = 'proforma.number_assigned';
    case ProformaMetadataChanged = 'proforma.metadata_changed';
    case DeliveryNoteCreated = 'delivery_note.created';
    case DeliveryNoteUpdated = 'delivery_note.updated';
    case DeliveryNoteStatusChanged = 'delivery_note.status_changed';
    case DeliveryNoteSigned = 'delivery_note.signed';
    case DeliveryNoteConverted = 'delivery_note.converted';
    case PurchaseInvoiceCreated = 'purchase_invoice.created';
    case PurchaseInvoiceUpdated = 'purchase_invoice.updated';
    case PurchaseInvoicePaid = 'purchase_invoice.paid';
    case PurchaseInvoiceCancelled = 'purchase_invoice.cancelled';
    case PurchaseInvoiceMetadataChanged = 'purchase_invoice.metadata_changed';
    case RecurringInvoiceCreated = 'recurring_invoice.created';
    case RecurringInvoiceActivated = 'recurring_invoice.activated';
    case RecurringInvoicePaused = 'recurring_invoice.paused';
    case RecurringInvoiceUpdated = 'recurring_invoice.updated';
    case RecurringInvoiceDeleted = 'recurring_invoice.deleted';
    case RecurringInvoiceCompleted = 'recurring_invoice.completed';
    case RecurringInvoiceExecuted = 'recurring_invoice.executed';
    case RecurringInvoiceFailed = 'recurring_invoice.failed';
    case RecurringInvoiceMetadataChanged = 'recurring_invoice.metadata_changed';
    case RecurringInvoiceCancelled = 'recurring_invoice.cancelled';
    case ClientCreated = 'client.created';
    case ClientUpdated = 'client.updated';
    case ClientDeleted = 'client.deleted';
    case ClientMetadataChanged = 'client.metadata_changed';
    case ProductCreated = 'product.created';
    case ProductUpdated = 'product.updated';
    case PaymentReceived = 'payment.received';
    case TaxMetadataChanged = 'tax.metadata_changed';
    case TaxValidityChanged = 'tax.validity_changed';
    case TaxExternalReferenceChanged = 'tax.external_reference_changed';
    case SeriesCreated = 'series.created';
    case SeriesUpdated = 'series.updated';
    case SeriesDeleted = 'series.deleted';
    case SeriesArchived = 'series.archived';
    case SeriesUnarchived = 'series.unarchived';
    case SeriesMarkedAsDefault = 'series.marked_as_default';
    case SeriesDemotedFromDefault = 'series.demoted_from_default';
    case SeriesYearReset = 'series.year_reset';
    case SeriesNumberConsumed = 'series.number_consumed';
}
