<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/**
 * UpdateProformaPublicLinkRequest - Public REST API v1 — PUT /v1/proformas/{uuid}/public-link.
 *
 *
 * `SchemaName` disambiguates the OpenAPI schema: Quote and Proforma declare
 * structurally identical request bodies, so without a unique name they would
 * collide in `components.schemas`.
 */
class UpdateProformaPublicLinkRequest
{
    /**
     *
     * @var \Factuarea\Sdk\Models\Components\UpdateProformaPublicLinkRequestAction $action
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateProformaPublicLinkRequestAction')]
    public UpdateProformaPublicLinkRequestAction $action;

    /**
     *
     * @var ?int $extendDays
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('extend_days')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $extendDays = null;

    /**
     * @param  \Factuarea\Sdk\Models\Components\UpdateProformaPublicLinkRequestAction  $action
     * @param  ?int  $extendDays
     * @phpstan-pure
     */
    public function __construct(UpdateProformaPublicLinkRequestAction $action, ?int $extendDays = null)
    {
        $this->action = $action;
        $this->extendDays = $extendDays;
    }
}