<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


class UpdateProductRequest
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $price = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateProductRequestItemKind $itemKind
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('item_kind')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateProductRequestItemKind|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateProductRequestItemKind $itemKind = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateProductRequestBaseUnit $baseUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('base_unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateProductRequestBaseUnit|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateProductRequestBaseUnit $baseUnit = null;

    /**
     * Whether this product takes part in document-driven stock movements: with `true`, issuing or receiving a document that includes it moves its stock automatically and the movement is recorded in the stock ledger. It only takes effect if your company also has stock management enabled; absent or `null` means `false`.
     *
     * @var ?bool $manageStock
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manage_stock')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $manageStock = null;

    /**
     *
     * @var ?bool $isActive
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_active')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isActive = null;

    /**
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateProductRequestCatalogAvailabilityMode $catalogAvailabilityMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('catalog_availability_mode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateProductRequestCatalogAvailabilityMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateProductRequestCatalogAvailabilityMode $catalogAvailabilityMode = null;

    /**
     *
     * @var ?string $sku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sku')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sku = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?float $stock
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stock')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $stock = null;

    /**
     *
     * @var ?float $lowStockThreshold
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('low_stock_threshold')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $lowStockThreshold = null;

    /**
     * Product amounts are read-only EUR: only `EUR` (or absence/null) is accepted.
     *
     * @var ?\Factuarea\Sdk\Models\Components\UpdateProductRequestCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Factuarea\Sdk\Models\Components\UpdateProductRequestCurrency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateProductRequestCurrency $currency = null;

    /**
     *
     * @var ?string $taxRateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxRateId = null;

    /**
     * A free map of up to 50 key→value pairs for storing arbitrary structured data (values are strings up to 500 characters). Unlike `custom_fields` — an ordered list of typed `{field, value}` pairs with display semantics, present on the six document resources — `metadata` is an unordered map for opaque integration data; a document may carry both. The master resources (Client, Supplier) have no `custom_fields`, so their `metadata` doubles as the custom-fields store.
     *
     *
     * **Reserved keys (read-only).** When the system auto-issues an invoice from a payment correlation (Stripe/GoCardless/MONEI), it writes `stripe_subscription_id`, `stripe_invoice_id`, `billing_reason`, `period_start` and `period_end` into that invoice metadata automatically. Do not set or overwrite them by hand — the platform owns them and a manual value may be replaced when the correlation runs.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Third-party integration key from your ERP/CRM. Partial update: an absent value is preserved. Free-form, up to 100 characters; unique per company.
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     *
     * @var ?string $impactToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('impact_token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $impactToken = null;

    /**
     * $tags
     *
     * @var ?array<string> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     * $specifications
     *
     * @var ?array<?string> $specifications
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('specifications')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string|null>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $specifications = null;

    /**
     * $optionGroups
     *
     * @var ?array<\Factuarea\Sdk\Models\Components\UpdateProductRequestOptionGroup> $optionGroups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('option_groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\UpdateProductRequestOptionGroup>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $optionGroups = null;

    /**
     * $configurations
     *
     * @var ?array<\Factuarea\Sdk\Models\Components\UpdateProductRequestConfiguration> $configurations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('configurations')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\UpdateProductRequestConfiguration>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $configurations = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $price
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateProductRequestItemKind  $itemKind
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateProductRequestBaseUnit  $baseUnit
     * @param  ?bool  $manageStock
     * @param  ?bool  $isActive
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateProductRequestCatalogAvailabilityMode  $catalogAvailabilityMode
     * @param  ?string  $sku
     * @param  ?string  $description
     * @param  ?float  $stock
     * @param  ?float  $lowStockThreshold
     * @param  ?\Factuarea\Sdk\Models\Components\UpdateProductRequestCurrency  $currency
     * @param  ?string  $taxRateId
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $externalId
     * @param  ?string  $impactToken
     * @param  ?array<string>  $tags
     * @param  ?array<?string>  $specifications
     * @param  ?array<\Factuarea\Sdk\Models\Components\UpdateProductRequestOptionGroup>  $optionGroups
     * @param  ?array<\Factuarea\Sdk\Models\Components\UpdateProductRequestConfiguration>  $configurations
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $price = null, ?UpdateProductRequestItemKind $itemKind = null, ?UpdateProductRequestBaseUnit $baseUnit = null, ?bool $manageStock = null, ?bool $isActive = null, ?UpdateProductRequestCatalogAvailabilityMode $catalogAvailabilityMode = null, ?string $sku = null, ?string $description = null, ?float $stock = null, ?float $lowStockThreshold = null, ?UpdateProductRequestCurrency $currency = null, ?string $taxRateId = null, ?array $metadata = null, ?string $externalId = null, ?string $impactToken = null, ?array $tags = null, ?array $specifications = null, ?array $optionGroups = null, ?array $configurations = null)
    {
        $this->name = $name;
        $this->price = $price;
        $this->itemKind = $itemKind;
        $this->baseUnit = $baseUnit;
        $this->manageStock = $manageStock;
        $this->isActive = $isActive;
        $this->catalogAvailabilityMode = $catalogAvailabilityMode;
        $this->sku = $sku;
        $this->description = $description;
        $this->stock = $stock;
        $this->lowStockThreshold = $lowStockThreshold;
        $this->currency = $currency;
        $this->taxRateId = $taxRateId;
        $this->metadata = $metadata;
        $this->externalId = $externalId;
        $this->impactToken = $impactToken;
        $this->tags = $tags;
        $this->specifications = $specifications;
        $this->optionGroups = $optionGroups;
        $this->configurations = $configurations;
    }
}