<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;

use Brick\DateTime\LocalDate;
/**
 * UpdatePurchaseInvoiceRequest - Public REST API v1 — PUT /v1/purchase_invoices/{uuid}.
 *
 *
 * Partial update: omitted fields are kept. Only allowed when
 * the purchase invoice is in `draft` status (the controller maps the
 * transition exception to 409 `invalid_status_transition`).
 */
class UpdatePurchaseInvoiceRequest
{
    /**
     *
     * @var ?string $supplierId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('supplier_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $supplierId = null;

    /**
     *
     * @var ?string $externalInvoiceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_invoice_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalInvoiceNumber = null;

    /**
     *
     * @var ?LocalDate $issuedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issued_on')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $issuedOn = null;

    /**
     * $lines
     *
     * @var ?array<\Factuarea\Sdk\Models\Components\UpdatePurchaseInvoiceRequestLine> $lines
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lines')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Factuarea\Sdk\Models\Components\UpdatePurchaseInvoiceRequestLine>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $lines = null;

    /**
     *
     * @var ?string $internalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('internal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $internalCode = null;

    /**
     *
     * @var ?LocalDate $receivedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('received_on')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $receivedOn = null;

    /**
     *
     * @var ?LocalDate $dueOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_on')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $dueOn = null;

    /**
     *
     * @var ?string $notes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('notes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $notes = null;

    /**
     * Up to 50 key-value pairs for storing additional structured data. Values must be strings up to 500 characters.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Extend fields. Basic SHAPE only; the `payment_method` allowlist,
     *
     * `tax_period` format and `tags` cardinality are validated by the
     * VO/Aggregate.
     *
     * @var ?string $internalNotes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('internal_notes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $internalNotes = null;

    /**
     *
     * @var ?string $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_method')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $paymentMethod = null;

    /**
     *
     * @var ?int $paymentTermsDays
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_terms_days')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $paymentTermsDays = null;

    /**
     *
     * @var ?int $bankAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_account_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $bankAccountId = null;

    /**
     *
     * @var ?string $expenseAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expense_account')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $expenseAccount = null;

    /**
     *
     * @var ?string $taxPeriod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_period')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxPeriod = null;

    /**
     *
     * @var ?bool $isReverseCharge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_reverse_charge')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isReverseCharge = null;

    /**
     * $tags
     *
     * @var ?array<string> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     * @param  ?string  $supplierId
     * @param  ?string  $externalInvoiceNumber
     * @param  ?LocalDate  $issuedOn
     * @param  ?array<\Factuarea\Sdk\Models\Components\UpdatePurchaseInvoiceRequestLine>  $lines
     * @param  ?string  $internalCode
     * @param  ?LocalDate  $receivedOn
     * @param  ?LocalDate  $dueOn
     * @param  ?string  $notes
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $internalNotes
     * @param  ?string  $paymentMethod
     * @param  ?int  $paymentTermsDays
     * @param  ?int  $bankAccountId
     * @param  ?string  $expenseAccount
     * @param  ?string  $taxPeriod
     * @param  ?bool  $isReverseCharge
     * @param  ?array<string>  $tags
     * @phpstan-pure
     */
    public function __construct(?string $supplierId = null, ?string $externalInvoiceNumber = null, ?LocalDate $issuedOn = null, ?array $lines = null, ?string $internalCode = null, ?LocalDate $receivedOn = null, ?LocalDate $dueOn = null, ?string $notes = null, ?array $metadata = null, ?string $internalNotes = null, ?string $paymentMethod = null, ?int $paymentTermsDays = null, ?int $bankAccountId = null, ?string $expenseAccount = null, ?string $taxPeriod = null, ?bool $isReverseCharge = null, ?array $tags = null)
    {
        $this->supplierId = $supplierId;
        $this->externalInvoiceNumber = $externalInvoiceNumber;
        $this->issuedOn = $issuedOn;
        $this->lines = $lines;
        $this->internalCode = $internalCode;
        $this->receivedOn = $receivedOn;
        $this->dueOn = $dueOn;
        $this->notes = $notes;
        $this->metadata = $metadata;
        $this->internalNotes = $internalNotes;
        $this->paymentMethod = $paymentMethod;
        $this->paymentTermsDays = $paymentTermsDays;
        $this->bankAccountId = $bankAccountId;
        $this->expenseAccount = $expenseAccount;
        $this->taxPeriod = $taxPeriod;
        $this->isReverseCharge = $isReverseCharge;
        $this->tags = $tags;
    }
}