<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Lifecycle status: `active` (in operation) and `archived` (withdrawn). There is no un-archive operation in this API, which is why archiving is published as irreversible. */
enum WarehouseStatus: string
{
    case Active = 'active';
    case Archived = 'archived';
}
