<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Factuarea\Sdk\Models\Components;


/** Lifecycle status of the location. Archiving one with active children is rejected: what is inside is emptied first. */
enum WarehouseLocationStatus: string
{
    case Active = 'active';
    case Archived = 'archived';
}
